### ISSUE TITLE
add chordal sparse SDP bridges (1 PSD to multiple smaller PSD constraints)

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/MathOptInterface.jl#1001]
I think there ought to be a Julia package for chordal matrix computations and manipulations, with some parts refactored from SumOfSquares (see https://github.com/JuliaOpt/SumOfSquares.jl/blob/master/src/Certificate/csp/ChordalExtensionGraph.jl) and COSMO (see https://oxfordcontrol.github.io/COSMO.jl/dev/decomposition/). CVXOPT has such a package in python/C called CHOMPACK: https://github.com/cvxopt/chompack. (Hypatia would use algorithmic tools too internally for nonsymmetric sparse PSD cones and sparse completable PSD cones.) A bridge in MOI or in such a chordal package can use these tools to help it perform chordal SDP transformations.

**Comment by joaquimg** [comment]
I would not do it as a bridge.
I think it should be a solver that gets an actual solver as argument, like Dualization or Pajarito.
This would facilitate passing parameters, for instance. It also allows cascading.

**Comment by blegat** [comment]
Even if it's not a bridge, the layer or meta-solver could be an `AbstractBridgeOptimizer` to facilitate the redirection of things.

**Comment by odow** [comment]
Chordal.jl has some tooling on this front:
https://github.com/tjdiamandis/Chordal.jl/blob/96fc18ac10fa5028bf7a5081ca2d9093025ee5e5/examples/sdp_lmi.jl

Closing because I think it's better left as an external package for now.
