### ISSUE TITLE
Integrality tolerance

### ISSUE THREAD

**Issue by remi-garcia** [jump-dev/MathOptInterface.jl#1012]
Default value for integrality tolerance is 10e-5 for [Gurobi](https://www.gurobi.com/documentation/9.0/refman/intfeastol.html) or [CPLEX](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.9.0/ilog.odms.cplex.help/CPLEX/Parameters/topics/EpInt.html). It would be nice to have a unique parameter for this. Is adding this parameter an option?

**Comment by odow** [comment]
So this has been discussed before: https://github.com/JuliaOpt/MathOptInterface.jl/issues/61

We're also considering a GSOC project to verify feasibility of models, which would require standardizing how "infeasibilility" is measured on a constraint-by-constraint basis.

To date, we've avoided adding tolerance attributes for a few reasons:
- we'd want to generalize "integrality" tolerance, potentially to a per constraint-type basis. For example:
    ```Julia
    struct Tolerance{F, S} <: MOI.AbstractOptimizerAttribute
    ```
- differences in how solvers may interpret the tolerance (absolute or relative? pre-solve or final solution (Yes, for some solvers, e.g., Gurobi, these can differ)?)
- differences in valid min/max values.

So, I'd say that the answer is a qualified yes for if adding tolerance parameters is an option. But we'd need to think hard about what and how to go about it.

**Comment by mlubin** [comment]
I think it's an exception rather than an rule when two solvers have consistent sets of tolerances. Differences in whether the tolerances are applied to the pre-solved problem or the original problem and before or after scaling are extremely common, as @odow mentioned.

Integrality *might* be simple enough that we can safely define a solver-independent version, but I'd want to see more evidence that this is true for most of the MIP solvers accessible through MOI, not just Gurobi and CPLEX.

**Comment by odow** [comment]
I'm also not sure how this would tie in with the bridging system. If you define a tolerance for a constraint, but it gets bridged, what does that mean?

**Comment by remi-garcia** [comment]
I understand why this is much more complex than I though.

If that's of any help I found the parameters for a few solver for this integrality tolerance:
Artelys Knitro: [`KN_PARAM_MIP_INTEGERTOL`](https://www.artelys.com/docs/knitro/3_referenceManual/userOptions.html#KN_PARAM_MIP_INTEGERTOL) (default: 10e-8)
BARON: [`AbsIntFeasTol`](https://minlp.com/downloads/docs/baron%20manual.pdf) (default: 10e-5)
CBC: [`bool setIntegerTolerance`](https://www.coin-or.org/Doxygen/Cbc/classCbcModel.html#abb2d59537f9d52fd6322b8be949212a7)(double value) (no default?)
GLPK: no parameter for integrality tolerance. Unless it is `tol_int` (default 10e-5) - _Absolute tolerance used to check if optimal solution to the current LP relaxation is integer feasible._
MOSEK: might be [`MSK_DPAR_MIO_TOL_ABS_RELAX_INT`](https://docs.mosek.com/9.1/capi/parameters.html#mosek.dparam.mio_tol_abs_relax_int) (default 10e-5)
SCIP: [no parameter for integrality tolerance](https://scip.zib.de/doc/html/PARAMETERS.php) (but feasibility tolerance for constraints available)

**Comment by odow** [comment]
Closing because I don't think there are good ways to abstract this. We should instead make sure that the solvers thoroughly document their options.

See this discussion in HiGHS for more details as well: https://github.com/ERGO-Code/HiGHS/pull/560#issuecomment-896507341
