### ISSUE TITLE
Add tests from Gurobi.jl

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/MathOptInterface.jl#1065]
Gurobi.jl and CPLEX.jl have some corner case tests that could benefit each other and other solvers.
The tests that are solver independent could be moved to MOI

**Comment by odow** [comment]
Examples include:

https://github.com/jump-dev/Gurobi.jl/blob/master/test/MOI/MOI_wrapper.jl#L225-L236
https://github.com/jump-dev/Gurobi.jl/blob/320fc27d8b6496ba9ac77429569243a2c667361b/test/MOI/MOI_wrapper.jl#L532-L582
https://github.com/jump-dev/Gurobi.jl/blob/320fc27d8b6496ba9ac77429569243a2c667361b/test/MOI/MOI_wrapper.jl#L861-L920
https://github.com/jump-dev/Gurobi.jl/blob/320fc27d8b6496ba9ac77429569243a2c667361b/test/MOI/MOI_wrapper.jl#L947-L958

https://github.com/jump-dev/CPLEX.jl/blob/e803dec9fc49898f452875795623bab2d7cd3abb/test/MathOptInterface/MOI_wrapper.jl#L242-L301

https://github.com/JuliaOpt/GLPK.jl/blob/83dd07f396f6f2ae32291461ae06d83b7e00a785/test/MOI_wrapper.jl#L148-L173
https://github.com/JuliaOpt/GLPK.jl/blob/83dd07f396f6f2ae32291461ae06d83b7e00a785/test/MOI_wrapper.jl#L317-L331

**Comment by odow** [comment]
Here is a more up-to-date list

- [ ] https://github.com/jump-dev/Gurobi.jl/blob/6484ba968b09526f13bb8cb5a1fe27abc82bb627/test/MOI/MOI_wrapper.jl#L1483-L1583
- [ ] https://github.com/jump-dev/Gurobi.jl/blob/6484ba968b09526f13bb8cb5a1fe27abc82bb627/test/MOI/MOI_wrapper.jl#L1350-L1365
- [ ] https://github.com/jump-dev/Gurobi.jl/blob/6484ba968b09526f13bb8cb5a1fe27abc82bb627/test/MOI/MOI_wrapper.jl#L1367-L1402
- [ ] https://github.com/jump-dev/Gurobi.jl/blob/6484ba968b09526f13bb8cb5a1fe27abc82bb627/test/MOI/MOI_wrapper.jl#L1039-L1287
- [ ] https://github.com/jump-dev/Gurobi.jl/blob/6484ba968b09526f13bb8cb5a1fe27abc82bb627/test/MOI/MOI_wrapper.jl#L708-L826
- [ ] https://github.com/jump-dev/Gurobi.jl/blob/6484ba968b09526f13bb8cb5a1fe27abc82bb627/test/MOI/MOI_wrapper.jl#L679-L706

I don't think there are any useful ones in CPLEX.

**Comment by odow** [comment]
Closing because all tests have been added, or are in open PRs.
