### ISSUE TITLE
Add function to retrieve the current processed node in the branch-and-bound tree

### ISSUE THREAD

**Issue by mikeKAH** [jump-dev/MathOptInterface.jl#1067]
Hi,
in the current documentation, I only found MOI.NodeCount() which returns the number of B&B nodes after the solving process. However, it would be great if one could also query the current processed node in a callback during the solving process.

kind regards, michael

**Comment by blegat** [comment]
Do you mean something like @odow suggested in https://github.com/JuliaOpt/JuMP.jl/pull/2127#discussion_r361815172?

**Comment by odow** [comment]
We won't be adding more attributes to MOI for callbacks. Use a solver-dependent callback instead (e.g., https://discourse.julialang.org/t/get-mipgap-in-gurobi-callbacks-jump-0-21/37232).

**Comment by mikeKAH** [comment]
> Do you mean something like what @odow suggested in [JuliaOpt/JuMP.jl#2127 (comment)](https://github.com/JuliaOpt/JuMP.jl/pull/2127#discussion_r361815172)?

I mean something like you had in MathProgBase: MathProgBase.cbgetexplorednodes( cb )

Sometimes you want to do operations in callbacks, for instance, only every 10 processed nodes.

**Comment by odow** [comment]
Use a solver dependent callback, and call the appropriate solver-dependent method.

Alternatively, use something like
```Julia
ncall = 0
function my_callback(cbdata)
    ncall += 1
    if mod(ncall, 10) != 0
        return
    end
    # ...
end
```

**Comment by odow** [comment]
Closing because we won't be adding new solver-independent attributes to MOI in the near-term (excluding https://github.com/jump-dev/MathOptInterface.jl/issues/1112).
