### ISSUE TITLE
Error in set_start_value

### ISSUE THREAD

**Issue by davide-f** [jump-dev/MathOptInterface.jl#1115]
Hi,

I am experiencing problems when using BilevelJuMP with Gurobi solver.
Having the set_start_value function working in bilevel optimization would be very important to speed up the calculations.
I am also advising the developers of BilevelJuMP and Gurobi.

I add few lines of code to reproduce the error. 
[report_error.txt](https://github.com/jump-dev/MathOptInterface.jl/files/4893669/report_error.txt)

**Comment by odow** [comment]
This is an issue with BilevelJuMP, not MathOptInterface. Closing in favor of https://github.com/joaquimg/BilevelJuMP.jl/issues/67
