### ISSUE TITLE
Model Writing Error Messages

### ISSUE THREAD

**Issue by ccoffrin** [jump-dev/MathOptInterface.jl#1116]
Given this model,
```
m = Model()
@variable(m, x)
@objective(m, Min, x^2)
```

The command, `write_to_file(m, "model.lp")` yields,
```
ERROR: MethodError: no method matching write_function(::IOStream, ::MathOptInterface.FileFormats.LP.Model{Float64}, ::MathOptInterface.ScalarQuadraticFunction{Float64}, ::Dict{MathOptInterface.VariableIndex,String})
```

The command, `write_to_file(m, "model.mps")` yields,
```
ERROR: MethodError: no method matching extract_terms(::MathOptInterface.FileFormats.MPS.Model{Float64}, ::Dict{String,Array{Tuple{String,Float64},1}}, ::String, ::MathOptInterface.ScalarQuadraticFunction{Float64}, ::Set{String})
```

Could these messages be improved?  Maybe something like, format X does not support constraint type Y?

**Comment by odow** [comment]
These examples should have failed on the `MOI.copy_to`, but they didn't for some reason.
https://github.com/jump-dev/MathOptInterface.jl/blob/26e0af44a254b545276b528298a390d34c378586/src/FileFormats/LP/LP.jl#L6-L16

**Comment by blegat** [comment]
`MOIU.Model` supports `SingleVariable`, `ScalarAffineFunction` and `ScalarQuadraticFunction` as objective by default:
https://github.com/jump-dev/MathOptInterface.jl/blob/26e0af44a254b545276b528298a390d34c378586/src/Utilities/model.jl#L411-L418
The following method should be added to the file `MathOptInterface.jl/src/FileFormats/LP/LP.jl`:
```julia
MOI.supports(::Model{T}, ::MOI.ObjectiveFunction{<:Union{MOI.SingleVariable, MOI.ScalarQuadraticFunction{T}}}) where T = false
```
