### ISSUE TITLE
incorrect number of variables in constraint after bridging

### ISSUE THREAD

**Issue by lkapelevich** [jump-dev/MathOptInterface.jl#1150]
```julia
using JuMP
using ECOS
model = Model();
@variable(model, x[1:5]);
@constraint(model, x in MOI.SecondOrderCone(17));
JuMP.set_optimizer(model, ECOS.Optimizer, bridge_constraints = true)
optimize!(model)

moi_model = JuMP.backend(model)
ci = MOI.get(moi_model, MOI.ListOfConstraintIndices{MOI.VectorOfVariables, MOI.SecondOrderCone}())[1]
fi = MOI.get(moi_model, MOI.ConstraintFunction(), ci)
@show length(fi.variables) # 5

bridge_opt = moi_model.optimizer
ci = MOI.get(bridge_opt, MOI.ListOfConstraintIndices{MOI.VectorOfVariables, MOI.SecondOrderCone}())[1]
fi = MOI.get(bridge_opt, MOI.ConstraintFunction(), ci)
@show length(fi.variables) # 17
```
should be able to throw an error, but instead a solver sees 17 variables.

On MOI v0.9.14

**Comment by odow** [comment]
Isn't this due to the incorrect dimension being given?

x-ref https://github.com/jump-dev/MathOptInterface.jl/issues/967

**Comment by lkapelevich** [comment]
I guess there are two things- the first is that there is no error thrown, the second is that the dimension of the function is inferred from the set instead of from the number of variables in the function, which felt unexpected. If the first thing was fixed the second wouldn't be an issue.

**Comment by blegat** [comment]
We should throw an error, where the dimension is read from can be either function or set since they should be the same

**Comment by lkapelevich** [comment]
I'm happy to make a pr if you let me know what you want to name the error type and when you think checks should happen

**Comment by odow** [comment]
JuMP should check the dimensions and throw a `DimensionMismatch` error before calling `add_constraint`. The underlying solvers could do this also, but that is more work.

**Comment by lkapelevich** [comment]
OK, in these guys https://github.com/jump-dev/JuMP.jl/blob/master/src/macros.jl#L296 without using `_error`?

**Comment by odow** [comment]
Probably actually here:
https://github.com/jump-dev/JuMP.jl/blob/5023f145edd8f2dae6632494a403cf484d5b379d/src/constraints.jl#L356-L359

Something like:
```Julia
function VectorConstraint(
    func::Vector{<:AbstractJuMPScalar}, set::MOI.AbstractVectorSet
)
    if length(func) != MOI.dimension(set)
        throw(DimensionMismatch(
            "dimension of the function $(length(func)) does not match the " *
            "dimension of the set $(set)."
        ))
    end
    return VectorConstraint(func, set, VectorShape())
end
```

**Comment by blegat** [comment]
I agree with @odow we want to avoid complicating to the macro code
