### ISSUE TITLE
Cannot Iterate on CleverDicts with Abstract Types

### ISSUE THREAD

**Issue by pulsipher** [jump-dev/MathOptInterface.jl#1157]
With the recent changes made to `CleverDict`, iterating on such with abstract keys and/or values leads to an assertion error due to the code shown below (after deletion occurs thus switching to the `OrderedDict`):
https://github.com/jump-dev/MathOptInterface.jl/blob/e512af8b9aa3cea737c0579a52b8247a96e2a0c7/src/Utilities/CleverDicts.jl#L291

Here is a simple contrived example:
```julia
using MathOptInterface
const MOIUC = MathOptInterface.Utilities.CleverDicts

data = MOIUC.CleverDict{MOI.VariableIndex, Number}()
new_key1 = MOIUC.add_item(data, 42.42)
new_key2 = MOIUC.add_item(data, 42.42)
delete!(data, new_key2)

for (k, v) in data
   println(v)
end
```
```
ERROR: TypeError: in typeassert, expected Pair{MathOptInterface.VariableIndex,Number}, got Pair{MathOptInterface.VariableIndex,Float64}
Stacktrace:
 [1] iterate(::MathOptInterface.Utilities.CleverDicts.CleverDict{MathOptInterface.VariableIndex,Number,typeof(MathOptInterface.Utilities.CleverDicts.key_to_index),getfield(MathOptInterface.Utilities.CleverDicts, Symbol("##1#2")){MathOptInterface.VariableIndex}}) at my_path\.julia\packages\MathOptInterface\R1y80\src\Utilities\CleverDicts.jl:291
 [2] top-level scope at .\REPL[37]:1
```

**Comment by odow** [comment]
This should probably be
```Julia
return convert(Pair{K, V}, el), State(i)
```

What is the use-case?

**Comment by pulsipher** [comment]
I use these `CleverDict`s in InfiniteOpt.jl as a convenient container for storing my parameter, variable, and constraint objects. Some of these objects have parametric types (e.g., different parameter sets) which necessitate the use of an abstract type for the container values since I do not know what sets the user will select. Then I iterate over these containers at a few places in my code (e.g., model transcription).  Here is a reference to the main `InfiniteModel` struct:
https://github.com/pulsipher/InfiniteOpt.jl/blob/8a25598d62a22cbf2c3d64729b89f0cb4d7d04fa/src/datatypes.jl#L839-L928

**Comment by odow** [comment]
Another option that probably doesn't hurt performance is to type the value as `Any`.
```Julia
# TODO: replace Any with <:VariableData{<:InfiniteVariable}} once
# https://github.com/jump-dev/MathOptInterface.jl/issues/1157 is fixed.
infinite_vars::MOIUC.CleverDict{InfiniteVariableIndex, Any}
```

**Comment by pulsipher** [comment]
Ya, that probably won't hurt the performance much, but you're right it sadly doesn't work (it was the first thing I tried). It only works with concrete types which are not readily possible in this application without introducing ambiguous type structures.
