### ISSUE TITLE
Invalid key, its hash must be > 0

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1165]
I get error with `CleverDict`:
https://travis-ci.org/github/jump-dev/SumOfSquares.jl/jobs/728541469#L663-L683
It seems to be complaining that a variable index has negative index during the reversion of the dictionary.
It might be because the bridged variable have negative index.

**Comment by odow** [comment]
Closed by https://github.com/jump-dev/MathOptInterface.jl/pull/1168?

**Comment by blegat** [comment]
Yes !
