### ISSUE TITLE
Bridge request: inner constraint of Indicator

### ISSUE THREAD

**Issue by Wikunia** [jump-dev/MathOptInterface.jl#1223]
It seems to make sense to use bridges for the right hand side or what I call inner constraint of an indicator constraint.

Such that `@constraint(b => { x + y >= z})` can be bridged with the `GreaterToLessBridge` to `@constraint(b => { -x - y <= -z})`

Currently this error is thrown:
```
ERROR: LoadError: Constraints of type MathOptInterface.VectorAffineFunction{Float64}-in-MathOptInterface.IndicatorSet{MathOptInterface.ACTIVATE_ON_ONE,MathOptInterface.GreaterThan{Float64}} are not supported by the solver and there are no bridges that can reformulate it into supported constraints.
```

I tried to implement it myself but I'm unsure how. Thought that I need to define sth like:

```
function MOI.supports_constraint(::Type{MOIBC.GreaterToLessBridge},
    ::Type{MOI.VectorAffineFunction}, ::Type{IS}) where {A,IS<:MOI.IndicatorSet{A,MOI.GreaterThan}}
    return true
end
```

Maybe someone can point me into the right direction on how the specialized version can be implemented as well as how one could implement the general version to use all available bridges for the inner constraint.

**Comment by blegat** [comment]
I would create a bridge parametrized by another bridge. Note that it cannot be parametrized by any bridge but only by subtypes of `SetMapBridge` and you should used the API of `SetMapBridge` to transform the constraint

**Comment by Wikunia** [comment]
Sorry I'm still unsure how to do this. How will this work internally? 
My thoughts:
- I have a bridge that supports all `IndicatorSet` constraints where I don't support the rhs directly but via a bridge?
   - How do I check that the solver supports the constraint via a bridge?
- I get the bridged version of the rhs constraint and return it as part of the new indicator constraint
   - How do I get the bridged version of a constraint?

**Comment by blegat** [comment]
Here is a sketch
```julia
struct Bridge{T, B<:SetMapBridge}
    con_idx::...
end
function bridge_constraint(::Type{Bridge{T, B}}, model, func, set) where {T, B}
    f = MOIU.eachscalar(func)
    new_func = MOIU.operate(vcat, T, f[1], MOI.Bridges.Constraint.map_function(B, f[2]))
    new_set = MOI.Indicator(MOI.Bridges.Constraint.map_set(B, set.set))
    return Bridge(MOI.add_constraint(model, new_func, new_set))
end
function MOI.supports_constraint(::Type{Bridge{T, B}}, ::Type{F}, ::Type{MOI.Indicator{S}}) where {T, B, F, S}
    return MOI.supports_constraint(B, MOIU.scalar_type(F), S)
end
```

**Comment by Wikunia** [comment]
That's super nice. Thanks a lot. One minor thing: I still have to use 
```
MOIB.add_bridge(lbo, CS.IndicatorBridge{T, MOIBC.GreaterToLessBridge{T}})
MOIB.add_bridge(lbo, CS.IndicatorBridge{T, CS.StrictlyGreaterToStrictlyLessBridge{T}})
```
so have a line for each subbridge that I want to support, right?

**Comment by blegat** [comment]
Yes, you need one line for each subtype of `SetMapBridge` you want to be used with this new indicator bridge.
