### ISSUE TITLE
Set request: Box or HyperRectangle

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1233]
```julia
struct Box{T}
    lower::Vector{T}
    upper::Vector{T}
end
```
which is a cartesian product if `Interval{T}` so `lower` and `upper` are allowed to have infinite values.
This has been requested by @migarstka for a long time and once again in https://github.com/oxfordcontrol/COSMO.jl/pull/129#issuecomment-771536349
It is also often requested from people in control where it's common to work with hyper-rectangles.

We would also have the bridges:
* `Box` to `Interval`s (`Bridges.Constraint.Scalarize`)
* `Interval` to `Box` (`Bridges.Constraint.Vectorize`)
* `Zeros`, `Nonnegatives` and `Nonpositives` to `Box` (otherwise, it would be scalarized and then vectorized to many 1-dimension boxes ^^)
* `Box` to `Nonnegatives` and `Nonpositives` (otherwise, it would be scalarized to `Interval` then bridged to a `GreaterThan` and a `LessThan` and then vectorized and it's many small 1-dim constraints)

**Comment by odow** [comment]
SCS 3.0 supports the Box cone: https://www.cvxgrp.org/scs/api/cones.html#cones
