### ISSUE TITLE
Support "nonscalar" variables (like complex numbers, intervals, sequences of intervals)?

### ISSUE THREAD

**Issue by dourouc05** [jump-dev/MathOptInterface.jl#1253]
For now, MOI only supports scalar variables, i.e. real numbers (or subsets thereof). Complex numbers can be implemented as a pair of real numbers, as in https://github.com/jump-dev/ComplexOptInterface.jl. For constraint programming, I would need to represent intervals (i.e. a pair of integer values: the beginning and the end of the interval) and sequences of intervals (defined based on a series of intervals), but also graphs. This kind of needs spans several engines: 

* CPLEX has specific types for these variables, and an interval cannot be constructed from other variables. In OPL (their modelling language): [interval](https://www.ibm.com/support/knowledgecenter/SSSA5P_20.1.0/ilog.odms.ide.help/OPL_Studio/opllang_quickref/topics/tlr_oplsch_interval.html) (also described more generally: https://www.ibm.com/support/knowledgecenter/SSSA5P_20.1.0/ilog.odms.cpo.help/refcppcpoptimizer/html/interval_variables.html) and [sequence](https://www.ibm.com/support/knowledgecenter/SSSA5P_20.1.0/ilog.odms.ide.help/OPL_Studio/opllang_quickref/topics/tlr_oplsch_sequence.html) (high-level overview: https://www.ibm.com/support/knowledgecenter/SSSA5P_20.1.0/ilog.odms.cpo.help/refcppcpoptimizer/html/constraints_groups.html).
* OscaR is another CP engine that has similar requirements. This one has sequences (https://bitbucket.org/oscarlib/oscar/src/dev/oscar-cp/src/main/scala/oscar/cp/core/variables/CPSeqVar.scala and subclasses CPHeadSeqVar, CPInsertSeqVar), but also graphs (https://bitbucket.org/oscarlib/oscar/src/dev/oscar-cp/src/main/scala/oscar/cp/core/variables/CPGraphVar.scala). 
* Gecode has set variables (https://www.gecode.org/doc-latest/MPG.pdf, Chapter 5).

How could this kind of variables fit into MOI? (Or an extension to MOI.) Typical functions cannot be applied on this kind of object: two intervals cannot really be summed up, or be greater than some constant, for instance. 

Maybe renaming SingleVariable as SingleScalarVariable/SingleRealVariable (and so on for the other related objects)? This would leave space for something like SingleIntervalVariable, SingleSequenceVariable (and vectors), etc., but also SingleComplexVariable. 

In a way, it could also solve some problems with `supports_constraint`: many CP constraints only make sense for integer variables (e.g., an array index), others are generalisable but are not always implemented as such (like counting values equal to something). With a SingleIntegerVariable, `supports_constraint` could directly check for the type of variables.

**Comment by blegat** [comment]
Here is another case where it would be useful to know the type of the variable.
Cbc also has issues when the variables are not binary in a SOS constraint: https://github.com/jump-dev/Cbc.jl/issues/151

**Comment by odow** [comment]
Is there any reason this needs to happen in MOI directly? My near-term goal is https://github.com/jump-dev/JuMP.jl/issues/2564, so I'm wary of adding lots of new functionality before we get 1.0 finished.

Functions like `is_binary` don't need to be:
```julia
function is_binary(model::MOI.ModelLike, x::MOI.VariableIndex)::Bool
    return MOI.is_valid(
        model, 
        MOI.ConstraintIndex{MOI.SingleVariable,MOI.ZeroOne}(x.value),
    )
end
```

I can't find the issue, but I suggested something like `CompositeVariableIndex` before in the context of JuMP. I think it was for interval variables, where 
```Julia
@variable(model, x, ConstraintInterval)
```
created `x.start`, `x.end` and `x.length`. This is something interesting to consider, but I don't think it needs to be part of MOI in the near-term.

**Comment by odow** [comment]
Yeah keep adding things to ConstraintProgrammingExtensions for now. Want to [give a talk at JuMP-dev](https://jump.dev/meetings/juliacon2021/) about it? It would be good to generate some wider discussion.

**Comment by dourouc05** [comment]
I'll submit an abstract for the workshop for sure! I suppose that a standard talk would be the best length for such a topic?

**Comment by blegat** [comment]
Yes, I would say you would need at least the length of a standard talk

**Comment by dourouc05** [comment]
OK, thanks a lot!

**Comment by odow** [comment]
We've made no progress on this, and I don't think we're going to anytime soon. To some extent, we have support for complex numbers, but it still requires adding two real variables. I think these ideas are perhaps best explored in a JuMP extension package.

**Comment by odow** [comment]
A good example for this would be local solver's `list` and `set` variable types: https://www.localsolver.com/docs/last/modelingfeatures/collectionvariables.html

I haven't worked through the details, but perhaps `x in List(10)` an `x in Partition()` could work to construct a list variable and a partition constraint. It's pretty clunky, and it depends on `x in Partition()` being able to work out that `x` is exactly a list variable. We couldn't support any old `VectorOfVariables in Partition`.

**Comment by odow** [comment]
I wonder if we should close this issue as out-of-scope. Supporting anything other than `VariableIndex` is a huge change, and we have the potential to either develop things as a JuMP extension, or to (ab)use the MOI definitions to support things like `x in Set` implies special stuff about `x`.

The most promising thing from the title is complex numbers. But we don't have any solvers at the MOI level requiring complex numbers, and we've shown that it can work at the JuMP level.

**Comment by blegat** [comment]
Yes, I'm unsure that we need it, we've also been able to have bridge act differently depending on properties of a variable by checking whether they are constrained to belong to some set in `final_touch`.

**Comment by odow** [comment]
To clarify, the closing of this: I talked to @dourouc05 yesterday, and we agreed that adding something other than `VariableIndex` is a big change.

The current suggestion for "interval" variables would be something like `x[1:2] in Interval()`, and then some support in JuMP to convert that into a `struct start::VariableRef; finish::VariableRef`.
