### ISSUE TITLE
FileFormats.MPS: support INDICATOR

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/MathOptInterface.jl#1266]
It seems most MILP solvers include INDICATOR as an extension of the MPS file format:
http://www-eio.upc.edu/lceio/manuals/cplex-11/html/reffileformatscplex/reffileformatscplex15.html
https://www.gurobi.com/documentation/9.1/refman/mps_format.html
(SCIP also)

**Comment by odow** [comment]
Format seems to be the same among solvers:

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/8177701/122493456-d29bb600-d03b-11eb-8a1a-72faf821b459.png">
