### ISSUE TITLE
Add VariableBasisStatus

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#1297]
`VariableBasisStatus` was removed here: https://github.com/jump-dev/MathOptInterface.jl/pull/679

However, we over-looked an edge case: without it, we can't tell if variables with free bounds with a `VariablePrimal` of `0.0` are in the (degenerate) basis or not.

This became a problem here: https://github.com/jump-dev/JuMP.jl/issues/2560, https://github.com/jump-dev/JuMP.jl/pull/2562

Given the redundancy with `ConstraintBasisStatus` on variable bounds, perhaps we just need 
```Julia
"""
    MOI.VariableInBasis

A variable attribute which indicates `true` or `false` if some variable is in 
the current optimal solution basis.
"""
struct MOI.VariableInBasis <: MOI.AbstractVariableAttribute end
```

cc @geoffleyland

**Comment by joaquimg** [comment]
Maybe a NoBoundRef or FreeBoundRef. Together with a Real (scalar set).

Or even simpler, a FreeVariableBasisStatus.
Returns error or nothing for bounded variables.

**Comment by odow** [comment]
I guess we could go:
```Julia
function FreeVariableRef(x::VariableRef)
    # Check lower_bound, upper_bound, is_fix, etc.
    return MOI.ConstraintIndex{MOI.SingleVariable,MOI.Reals}(x.index.value)
end
```
and define something along the likes of
```Julia
function MOI.get(
    model::Optimizer,
    ::MOI.ConstraintBasisStatus,
    c::MOI.ConstraintIndex{MOI.SingleVariable,MOI.Reals},
)
    return in_basis(MOI.VariableIndex(c.value)) ? MOI.BASIC : MOI.SUPER_BASIC
end
```
But that's a pretty unusual interpretation.

**Comment by mlubin** [comment]
Can you point to solver documentation on non-basic free variables? Which solvers have this concept?

**Comment by joaquimg** [comment]
Here is Xpress:

https://www.fico.com/fico-xpress-optimization/docs/latest/solver/optimizer/HTML/XPRSgetbasis.html

**Comment by odow** [comment]
GLPK has
![image](https://user-images.githubusercontent.com/8177701/115126524-c0919d00-a023-11eb-89bc-67957eee3697.png)

CPLEX has
![image](https://user-images.githubusercontent.com/8177701/115126617-6c3aed00-a024-11eb-9df8-9c4c3b82e187.png)

**Comment by mlubin** [comment]
Maybe we should stop fighting against the solver APIs by reviving `VariableBasisStatus`, and saying that `SingleVariable` constraints don't have a `ConstraintBasisStatus`.
