### ISSUE TITLE
Deprecate Allocate-Load

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1341]
The purpose of Allocate-Load is to be able to communicate the model in two-pass across layers without the need to create intermediate `CachingOptimizer`.
However, it's not yet implemented by the bridge optimizers and it's not clear to me whether there is a way to do this without complicating the job of creating new bridges for users.
This new features https://github.com/jump-dev/MathOptInterface.jl/pull/1286 allows to pass non-bridges constraints across layers which allows to avoid copying the function as the destination model of the copy can get the `CanonicalConstraintFunction` directly from the source model.
So a model needed Allocate-Load could implement `MOIU.pass_nonvariable_constraints` instead and it would work if no constraint if bridges.
To also work with bridging constraints, it should also implement `MOI.add_constraint` but only allow it to be called during the copy operation.
This is what is done for MatrixOfConstraints: https://github.com/jump-dev/MathOptInterface.jl/pull/1287.
In fact, I expect most solver needing Allocate-Load to be rewritten with MatrixOfConstraints like Clp in https://github.com/jump-dev/Clp.jl/pull/111.
The only two exceptions are CSDP and SDPA but there is no point in keeping the Allocate-Load API just for these two.
I'll keep this open until we're close to releasing v0.10 to evaluate if things happens as expected and then we can decide.

**Comment by odow** [comment]
There are a few major benefits of getting rid of allocate-load
 - Code simplicity. Currently, there is a whole file of code that isn't really used, and just complicates the whole `copy` story. We don't need three ways of implementing copy!
 - Getting rid of the `pass_attrs` and `pass_cons` to the `copy` functions. These really reduce the readability of the copy operations and add to the strain on inference.

I still don't really understand the need for `MOIU.pass_nonvariable_constraints`. If solvers have unique copy requirements concerning the order of variables, can't they just write a new `copy_to`? We don't want this copy being too generic that solvers can patch different parts of it.

**Comment by blegat** [comment]
I don't know if many solvers are going to use `MOIU.pass_nonvariable_constraints`. The main use-case is MatrixOfConstraints.

**Comment by odow** [comment]
Time to revisit this @blegat?

**Comment by blegat** [comment]
When updating the solvers using it for MOI v0.10, I'll try at the same time to stop using allocate-load and verify it's as expected.

**Comment by odow** [comment]
@blegat do you have time at some point to try migrating one of the allocate-load solvers? This is one of the blockers for MOI 0.10.

**Comment by blegat** [comment]
Updating the conic solvers is the next item on my TODO list after https://github.com/jump-dev/MathOptInterface.jl/pull/1461
