### ISSUE TITLE
bug with error throwing

### ISSUE THREAD

**Issue by etienneINSA** [jump-dev/MathOptInterface.jl#1357]
[This throw](https://github.com/jump-dev/MathOptInterface.jl/blob/ce19dce9147a8040d8582c79179b541b64e1ce31/src/attributes.jl#L472) does not provide an error message, where `UnsupportedSubmittable` requires one.

**Comment by blegat** [comment]
Thanks for reporting it, we should add a default fallback with empty message like https://github.com/jump-dev/MathOptInterface.jl/blob/7006a175221fa0cbb39d43337865ed2bfa88e894/src/attributes.jl#L63
