### ISSUE TITLE
[Compat] BenchmarkTools v1

### ISSUE THREAD

**Issue by Azzaare** [jump-dev/MathOptInterface.jl#1364]
Would it be possible to add the compat for BenchmarkTools.jl v1 and tag a new version of MOI?

**Comment by blegat** [comment]
I just did `] up` and Pkg downgraded 22 packages just to update BenchmarkTools to v1.0

**Comment by odow** [comment]
@blegat looks like quite a few solvers broke: https://github.com/jump-dev/SolverTests/runs/2646391301.

Can we simplify the `release-0.9` branch to only include the BenchmarkTools patch?

x-ref: https://github.com/jump-dev/MathOptInterface.jl/commit/7674393fae4e4301d05c490f31c987c93a64df19#r51199237

**Comment by blegat** [comment]
We should at least fix the regressions introduced in v0.9.21 so we need the bug fixes (https://github.com/jump-dev/MathOptInterface.jl/pull/1354, https://github.com/jump-dev/MathOptInterface.jl/pull/1367) and perf fixes (https://github.com/jump-dev/MathOptInterface.jl/pull/1318)

**Comment by odow** [comment]
0.9.22 is released.

**Comment by Azzaare** [comment]
Thanks @odow , that was quick :D
