### ISSUE TITLE
Order of solutions

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1372]
When the termination status is `OPTIMAL`, do the solver need to guarantee that the optimal solution is the first one ?
If this is the case, then this is a bug: https://github.com/jump-dev/MosekTools.jl/issues/66
In fact, we kind of assume it the tests already since we only ever test with the first solution.
Is this in the documentation somewhere ?
I remember we discussed about that, see e.g. https://github.com/jump-dev/JuMP.jl/pull/2512#discussion_r592657852

**Comment by odow** [comment]
> When the termination status is OPTIMAL, do the solver need to guarantee that the optimal solution is the first one ?

Yes. If this is not documented, it should be. It's the only reasonable thing to do.
