### ISSUE TITLE
A minimal NLP interface to MOI?

### ISSUE THREAD

**Issue by jd-foster** [jump-dev/MathOptInterface.jl#1396]
This is more a question than an issue...
There was a discussion with @mlubin at the NLopt repo around a designing an simpler API for nonlinear optimization based on MOI here: https://github.com/JuliaOpt/NLopt.jl/issues/128#issuecomment-468928060

How much interest do you think there would be for contributing/developing this? I can imagine there is a reasonably common use case where a non-expert user of optimization has a list of functions/vectors that form their objective and constraints, and they 'just' want to call a Julia function that 'solves' the problem using an MOI wrapped solver, without translating the problem directly into say JuMP. Mostly curious for perspectives; this functionality may also encourage solver/algorithm developers to hook into MOI.

**Comment by mohamed82008** [comment]
Check out https://github.com/mohamed82008/Nonconvex.jl.

**Comment by odow** [comment]
> How much interest do you think there would be for contributing/developing this?

I'm sure there would be interest. But this seems like a case for a package other than MathOptInterface. 

Nonconvex.jl is an excellent option. 

Other options are:
 - https://github.com/SciML/GalacticOptim.jl
 - https://github.com/JuliaSmoothOptimizers/NLPModels.jl

Presumably one could also write an Optim interface to Ipopt.

There will be a section on nonlinear programming at the upcoming [JuMP-dev](https://jump.dev/meetings/juliacon2021/). It should be a good starting point to get a lot of people interested in similar things together.

**Comment by jd-foster** [comment]
Great links, thanks fellow Oceania optimisers. 😀

How "automatic" is the Nonconvex.jl link to MathOptInterface, in the sense that a new wrapped solver for MathOptInterface can be dropped in to a solve using Nonconvex?

**Comment by odow** [comment]
> How "automatic" is the Nonconvex.jl link to MathOptInterface

That might be something better discussed in the Nonconvex.jl repo.

I'm going to close this issue as out-of-scope for MathOptInterface. We should focus effort on this front into existing packages.

**Comment by jd-foster** [comment]
No worries, I'll have a closer look at the other repos. Thanks again.
