### ISSUE TITLE
Simplify creation of MOI Layers

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/MathOptInterface.jl#1399]
Like this comment (https://github.com/jump-dev/MathOptInterface.jl/issues/1397#issuecomment-864609898) highlighted we have been creating MOI layers.

Besides MOIU layers like:
CachingOptimizer
LazyBridgeOptimizer

And the classic:
https://github.com/jump-dev/Dualization.jl

Other layers include:
https://github.com/jump-dev/DiffOpt.jl
https://github.com/jump-dev/ParametricOptInterface.jl
https://github.com/joaquimg/QuadraticToBinary.jl

Many of them only extend part of the MOI API, but for all other methods they just have to create a bunch of forwarding methods to simply send the work to the next level.

We could have an `AbstractExtensionOptimizer` that implements all methods by forwarding them to the `inner` backend.

There might already be another issue about it. We discussed similar things in the past (@odow ), we even considered a macro (which might be overkill). @blegat even suggested using `AbstractBridgeOptimizer` as a quick hack in some extension.

**Comment by odow** [comment]
A good way to start this may even just be a documentation page, which contains a template of forwarding every method to the inner optimizer. It's easy to miss some, or to use the wrong type signatures.

**Comment by odow** [comment]
AmplNLWriter is another one of these now: https://github.com/jump-dev/AmplNLWriter.jl/pull/141#discussion_r697768932

**Comment by odow** [comment]
We seem to be getting on okay without this. It's tricky to document, because there is no one-size-fits-all approach. I don't actually think there is such a thing as an easy layer, you're really just writing a new optimizer. I might close this unless someone objects.

**Comment by odow** [comment]
Closing because I don't know a good way to do this. At the lowest level, layers can just implement the two-argument version of `optimize!(model, src)`. But anything else and it becomes problem-specific which little bits need to be implemented. Writing new layers happens infrequently enough that I think we're okay without it anyway.
