### ISSUE TITLE
Reorder fields of ScalarQuadraticFunction

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1406]
I always felt having quadratic terms first and affine terms second would make more sense so that the degree of the terms is decreasing. Here, the degrees are 1, 2, 0 which is weird.
https://github.com/jump-dev/MathOptInterface.jl/blob/6bbdf82ec65381ea27f86b2e12de8c1204e23372/src/functions.jl#L172-L176

**Comment by odow** [comment]
I agree. And I constantly have to look at the documentation to see which way around it is.

Maybe we could just add a constructor in the other order? Since the types are different, it will always be apparent which one the user intended.

**Comment by blegat** [comment]
We could have a constructor in the order order with a depwarn but I don't think we should keep it. Having two ways to make something just makes a code using MOI less readable

**Comment by blegat** [comment]
Another option would be to have the affine function as a subfield of the quadratic function. It is what JuMP does and it could simplify a lot of code in `Utilities/functions`. Then `ScalarQuadraticFunction` would be unmutable because the only reason it's mutable is the constant.

**Comment by odow** [comment]
This would make a lot of sense, but it's pretty breaking without a deprecation path.

**Comment by blegat** [comment]
Yes, we would need a nice fallback with a warning. By the way, another reason for reconsidering this is that having an affine function inside the quadratic function would create 2 allocations in older Julia version which is not the case anymore since immutable struct containing fields on the heap can still be allocated on the stack.
