### ISSUE TITLE
Test DualStatus

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1411]
If `config.duals` is `false`, we should probably check that `DualStatus` is NO_SOLUTION. With DeprecatedTests, this isn't really an option since that would isallow solvers that supports duals to run tests without duals.
With the new tests, they can exclude the DualStatus attribute in addition to setting `duals` to `false`.
In fact, the docstring might also say that this is a mandatory attribute that should return NO_SOLUTION in case duals are not supported. It's kind of implicit but for a constraint programming solver for instance, it may be unclear that you actually need to implement this:
https://github.com/jump-dev/MathOptInterface.jl/blob/98608b82a82cb5e365f9f1b0c4dd32dd6dfd186d/src/attributes.jl#L1663-L1671
See https://github.com/JuliaOpt/NLopt.jl/issues/169

**Comment by odow** [comment]
There is `default_status_test` in `modelike.jl`. We should run that instead.

We have too many tests that are testing too many things. We need one test per thing.

**Comment by blegat** [comment]
I guess with the new `runtests`, NLopt will run this test by default even if `duals` is false so this resolve the issue.

**Comment by odow** [comment]
Yes. There are already existing tests for almost every situation. They're just hard for solvers to find and understand if/when they should run them.
