### ISSUE TITLE
Consistent naming for sets

### ISSUE THREAD

**Issue by dourouc05** [jump-dev/MathOptInterface.jl#1459]
No concrete set in MOI has the word `set` in it, with the exception of `IndicatorSet`. Moreover, all the abstract sets have the word `set` in their name. 

By the way, indicators are not covered in https://jump.dev/MathOptInterface.jl/dev/manual/constraints/, I think they should be. 

It would also be useful to document a naming guide for sets, as it's probably one of the first things that are extended in MOI. Currently, the best place looks like https://jump.dev/JuMP.jl/stable/developers/extensions/#Define-a-new-set, but I think it would rather belong to MOI's doc. 

- [ ] MOI Indicator instead of IndicatorSet: https://github.com/jump-dev/MathOptInterface.jl/pull/1475
- [ ] MOF Indicator instead of IndicatorSet: https://github.com/jump-dev/MathOptFormat/pull/18
- [x] MOI Zeros, Reals to ZeroCone, RealCone: https://github.com/jump-dev/MathOptInterface.jl/pull/1477
- [x] MOF Zeros, Reals to ZeroCone, RealCone: abandoned
- [ ] MOI Complements to something else
- [ ] MOF Complements to something else
- [ ] Naming conventions: https://github.com/jump-dev/MathOptInterface.jl/pull/1476
- [ ] Order of arguments

**Comment by odow** [comment]
So you're suggestion it be renamed to `Indicator`? I'd support this.

> It would also be useful to document a naming guide for sets

:+1: to this. 

Some thoughts: 

* Conic sets should end in `Cone`
* Matrix-valued sets should provide both `XXXConeSquare` and `XXXConeTriangle` versions
* Follow established naming conventions if at all possible:
  - Conic cone from CVX
  - Constraint programming sets from MiniZinc
* Prefer singular `Integer` instead of `Integers`

There are a couple of other violations of these rules:
 - Nonnegatives -> NonnegativeCone
 - Nonpositives -> NonpositivesCone
 - Zeros -> ZeroCone
 - Reals -> RealCone

**Comment by dourouc05** [comment]
Another note about sets: we should settle for an order of arguments, mostly where the dimension should be put (before or after the other arguments?). I don't have any preference for any order (and I have used both for CP sets, I reckon).

**Comment by dourouc05** [comment]
To have more uniformity in the way sets are named, maybe `Complements` should be changed to `Complementarity`? KNITRO and AMPL use the `complements` keyword, but it's infix (`f complements g`). GAMS uses their own syntax, `=n=`. AIMMS uses a mix of `ComplementaryVariable` and `Complement`, with a totally different syntax. [Yaml files](https://www.recs-solver.org/ug_model_files.html) use `|`. Nothing really matches the syntax MOI provides.

**Comment by blegat** [comment]
Zeros is indeed a cone as it is the singleton witg the origin. Reals is a non-pointed cone and it is also a linear space. Both Zeros and Reals are linear spaces. Maybe we could name them ZeroSpace ane RealSpace?
Every linear space is a cone and every cone is a set. The naming should follow the most specific family

**Comment by mlubin** [comment]
Avoiding "Set" in concrete set names is reasonable enough. I'm not really seeing the motivation for renaming all sets that might be interpreted as a cone (as @blegat mentioned, some could also be linear spaces). Has anyone been confused by `Nonnegatives` and `Zeros`? It's also a bit strange to create sweeping naming conventions and then privilege names from CVX and MiniZinc that could conflict with these conventions. CVX has a defined list of atoms; does it have a list of cones too?

**Comment by dourouc05** [comment]
The reference to other software is mostly to deal with cases where you have a lot of different names. In my opinion, the best example is https://sofdem.github.io/gccat/gccat/Cinverse.html: you have at least three extremely different names that are used for the same constraint. 

> inverseChanneling in Choco, channel in Gecode, inverse in MiniZinc, assignment in SICStus.

I'm not dogmatic about the `Cone` in the name of cones; however, the plural in sets really seems to be unjustified. In my opinion, having a dimension in `Zeros` or `Reals` is just a shortcut to having a scalar set and having every function in this scalar set, instead of having a vector. I don't think that sets should be named for shortcuts. This would mean that all sets are renamed to have a singular noun: that would make MOI easier to grasp for newcomers, because that's one thing fewer to remember about the various sets.

**Comment by odow** [comment]
Closing because we now have naming guidelines and the worst-offender (IndicatorSet) has been renamed.
