### ISSUE TITLE
Parametrize GenericModel with objective type

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1470]
We could have GenericModel parametrized by the objective type so that a solver can set it to `MOI.ScalarAffineFunction{Float64}` in its `OptimizerCache` type so that it won't have to worry about other cases.
For instance,
https://github.com/jump-dev/Clp.jl/pull/114/files#diff-18c6af231f3facc5ba10dd45231da349efda22ecd8d68a4661dee8027bc413a7R296-R297
is incorrect as it will throw a convert error if the objective is quadratic instead of an UnsupportedAttribute error.

**Comment by odow** [comment]
I also wondered about just storing three fields for the three objective types, or having a separate `Objective` structure.

**Comment by odow** [comment]
I also just noticed that the current approach leads to inference errors, because of this:
https://github.com/jump-dev/MathOptInterface.jl/blob/830ef4eaca8caa8625be277f2e41dd2a4c5348d6/src/Utilities/model.jl#L694-L695

I'll have a go after I finish #1468
