### ISSUE TITLE
VariableConstraint

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1471]
The way variables are represented internally by `MOIU.GenericModel` is encapsulated in the following 4 lines
https://github.com/jump-dev/MathOptInterface.jl/blob/a1d3ed961176f65ec9f74afad455ecedbb1ce8d3/src/Utilities/model.jl#L993-L1001
We could factor them out into a `ModelLike` supporting only these `SingleVariable` constraints.
This would allow MOI wrapper that need this to just have this as a field as well and not have to redo all the work.
That would apply to all solvers currently having the `VariableInfo` struct.
The issue is that this is currently hardcoded for a few `SingleVariable` constraints of interest.

**EDIT**: just notice that this is close to what https://github.com/jump-dev/MathOptInterface.jl/pull/1468 does

**Comment by odow** [comment]
Not in favor of this. 

I think #1468 is sufficient in the near-term. We can add functionality to simplify solver interfaces post 1.0. (We keep having scope-creep on our 0.10 release, so I'd rather focus on that.) I also don't think it's breaking to modify internal fields of `Model` later on.

**Comment by blegat** [comment]
It is breaking as solvers access the lower and upper bound vectors directly:
https://github.com/jump-dev/Clp.jl/pull/114/files#diff-18c6af231f3facc5ba10dd45231da349efda22ecd8d68a4661dee8027bc413a7R310-R311

**Comment by odow** [comment]
Ah. I guess #1468 is almost exactly what you're after. It just needs a bit more logic moved from model to `box.jl`. 

I might make a separate type for the MatrixOfConstraint use-case. it can re-use some of the logic, but having `Box` appear in two places is what's confusing.

**Comment by blegat** [comment]
As discussed in https://github.com/jump-dev/MathOptInterface.jl/pull/1468#discussion_r670931850, I don't see what's confusing. The box in itself is a well defined object. It's only constructed differently in MatrixOfConstraints and AbstractModel but it would make sense to reuse the same structure. In fact, the Box struct could also be an `AbstractVectorSet` which is the cartesian product of Interval's. This is a request we sometimes get, e.g. from COSMO (although MatrixOfConstraints might resolve COSMO's use case).

So it seems intuitive to me that we have a Box object which is a hyperrectangle (and might or might not be a AbstractVectorSet now or in the future) and a ModelLike object which stores SingleVariable constraints internally as a big VectorOfVariable-in-Box constraint.

**Comment by odow** [comment]
Closed by #1468 

Solvers can use `SingleVariableConstraints` and handle `supports_constraint` separately.
