### ISSUE TITLE
Parametrize GenericModel with variable constraints

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1502]
The conic solvers don't support any variable constraints. So when implementing `copy_to` from their `OptimizerCache`, they will all need to check that no constraint variable is set. LP solvers supports some of them but not all so they will need to check that the ones they support are not set.
One way to improve the situation would be to allow `GenericModel` to have different type of variable containers.

**Comment by odow** [comment]
Can't solvers just overload `supports_constraint`?

**Comment by blegat** [comment]
It would but I feel it's best too just make GenericModel modular.
Now it's just a combination of three submodels: one for the objective, one for the scalar variables constraints and one for the rest. It's just dispatching calls to the correct submodel, it's not specific at all to what is used as submodel. Allowing it to have any submodel would enable any combination of models. That also allows supporting other kind of SingleVariable constraints and other function as objective.
