### ISSUE TITLE
Implement `getkey` for DoubleDicts

### ISSUE THREAD

**Issue by jd-lara** [jump-dev/MathOptInterface.jl#1522]
Related to POI, in some cases to get the key from a particular key for a value. For instance, recover the parametrized original function when calling `MOI.get(model::ParametricOptimizer, attr::MOI.ConstraintFunction, ci::MOI.ConstraintIndex{F, S})`

**Comment by odow** [comment]
Can you link to the use-case?

**Comment by jd-lara** [comment]
@odow I want to recover the key from this dict https://github.com/jump-dev/ParametricOptInterface.jl/blob/0f9f0bb76a56eb70c93b0e30ba9460a83036e0f9/src/ParametricOptInterface.jl#L47

**Comment by odow** [comment]
Given what?

**Comment by odow** [comment]
`getkey` assumes you know the key?

```Julia
help?> getkey
search: getkey

  getkey(collection, key, default)

  Return the key matching argument key if one exists in collection, otherwise return default.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> D = Dict('a'=>2, 'b'=>3)
  Dict{Char, Int64} with 2 entries:
    'a' => 2
    'b' => 3
  
  julia> getkey(D, 'a', 1)
  'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
  
  julia> getkey(D, 'd', 'a')
  'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
```

**Comment by jd-lara** [comment]
> Given what?

The index, and see if it is indexed already or maybe it was converted to quadratic and I need to go search in the quad cache. I can also use other patterns but it seemed easier to concatenate the searches.

**Comment by odow** [comment]
Do you mean `haskey`? I'm confused as to where this gets used. Can you sketch an example?

**Comment by jd-lara** [comment]
all `getkey` does is return a default value if the key isn't in the dict. It summarizes this pattern: 

```julia
mydict = Dict("A" => 1, "B" =>3)

# this: 
value = haskey(mydict, "C") ? mydict["C"] : 0.0

# is the same as: 

value = getkey(mydict, "C", 0.0)

```

**Comment by jd-lara** [comment]
This is the function in POI I was using but I can write it with haskey instead. 

```julia
function MOI.get(model::ParametricOptimizer, attr::MOI.ConstraintFunction, ci::MOI.ConstraintIndex{F, S}) where {F, S}
    # Check if the index was cached as Affine expression
    if !isempty(model.affine_constraint_cache)
        value = get(model.affine_constraint_cache, ci, MOI.ScalarAffineFunction(Array{MathOptInterface.ScalarAffineTerm{Float64}, 1}(), 0.0))
        !iszero(value) && return value
    # Check if the index was cached as a Quadratic
    elseif !isempty(model.quadratic_added_cache)
        value = getkey(model.quadratic_added_cache, ci, MOI.ScalaQuadraticFunction(Array{MathOptInterface.ScalarAffineTerm{Float64}, 1}(), 0.0))
        !iszero(value) && return value
    else
        return MOI.get(model.optimizer, attr, ci)
    end
end
```

**Comment by odow** [comment]
`getkey` doesn't do what you think it does, and your function has a few things wrong with it. In particular, it may return `nothing`, and it will only check the `quadratic_added_cache` if the `affine_constriant_cache` is empty.

Did you mean something like:
```Julia
function MOI.get(
    model::ParametricOptimizer,
    attr::MOI.ConstraintFunction,
    ci::MOI.ConstraintIndex{F,S},
)::F where {F,S}
    value = get(model.affine_constraint_cache, ci, nothing)
    if value !== nothing
        return value
    end
    value = get(model.quadratic_added_cache, ci, nothing)
    if value !== nothing
        return value
    end
    return MOI.get(model.optimizer, attr, ci)
end
```
But this might still be wrong since `value` might not always be `F`? Don't you need to write separate functions for affine and quadratic functions?

**Comment by jd-lara** [comment]
@odow yeah the code I pasted was hasty, this is what I pushed https://github.com/jump-dev/ParametricOptInterface.jl/pull/59/commits/b0d3091e5a9c252c853b8cfd3de486b48c757855

**Comment by odow** [comment]
Closing because we don't need to implement this. We already overload `get` with three arguments which is needed for this use-case.
