### ISSUE TITLE
Common test failures to investigate

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#1571]
These are some common test failures to investigate. Some might be problems in the solvers. Others might be issues with the test.

- [x] test_model_LowerBoundAlreadySet and test_model_UpperBoundAlreadySet: https://github.com/jump-dev/MathOptInterface.jl/issues/1431

- [x] test_constraint_ConstraintDualStart and test_constraint_ConstraintPrimalStart: #1572

- [x] test_linear_integration_Interval

This works with HiGHS, but not through the caching optimizer (I think this is an upstream bug in HiGHS https://github.com/jump-dev/HiGHS.jl/issues/70)

```Julia
julia> model = MOI.Bridges.full_bridge_optimizer(
               MOI.Utilities.CachingOptimizer(
                   MOI.Utilities.UniversalFallback(MOI.Utilities.Model{Float64}()),
                   HiGHS.Optimizer(),
               ),
               Float64,
           )
MOIB.LazyBridgeOptimizer{MOIU.CachingOptimizer{HiGHS.Optimizer, MOIU.UniversalFallback{MOIU.Model{Float64}}}}
with 0 variable bridges
with 0 constraint bridges
with 0 objective bridges
with inner model MOIU.CachingOptimizer{HiGHS.Optimizer, MOIU.UniversalFallback{MOIU.Model{Float64}}}
  in state EMPTY_OPTIMIZER
  in mode AUTOMATIC
  with model cache MOIU.UniversalFallback{MOIU.Model{Float64}}
    fallback for MOIU.Model{Float64}
  with optimizer A HiGHS model with 0 columns and 0 rows.

julia> MOI.Test.test_linear_integration_Interval(model, config)

Presolving model
1 rows, 1 cols, 1 nonzeros
0 rows, 0 cols, 0 nonzeros
Presolve : Reductions: rows 0(-1); columns 0(-2); elements 0(-2) - Reduced to empty
Solving the original LP from the solution after postsolve
Model   status      : Optimal
Objective value     :  1.0000000000e+01
HiGHS run time      :          0.00
Test Failed at /Users/oscar/.julia/packages/MathOptInterface/T803v/src/Test/test_linear.jl:1848
  Expression: ≈(MOI.get(model, MOI.DualObjectiveValue()), T(10), atol = atol, rtol = rtol)
   Evaluated: -10.0 ≈ 10.0 (atol=1.4901161193847656e-8, rtol=1.4901161193847656e-8)
```

**Comment by matbesancon** [comment]
Otherwise the biggest pain points on many solvers:
- accepting duplicate names but throwing on get only, requires maintaining an internally inconsistent state
- keeping track of the list of attributes set

**Comment by odow** [comment]
* For the quadratic objective it probably is okay to skip it. 
 * We spent a fair bit of time on the duplicate name issue. The current behavior will stay. #674 asks for a utility to help with the names
 * Attributes are needed to be kept track of. Things like `ObjectiveSense` just require an additional flag.

**Comment by odow** [comment]
Closing as done. 

For the objective function question, you can add:
```julia
function MOI.get(model::Optimizer, ::MOI.ObjectiveFunction{F}) where {F}
    obj = MOI.get(
        model,
        MOI.ObjectiveFunction{MOI.ScalarAffineFunction{Float64}}(),
    )
    return convert(F, obj)
end
```
