### ISSUE TITLE
supports AbstractConstraintAttribute broken for bridges

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#1572]
HiGHS doesn't support `ConstraintDualStart`, so any bridged constraint shouldn't either. But yet:
```julia
julia> model = MOI.Bridges.full_bridge_optimizer(HiGHS.Optimizer(), Float64)
MOIB.LazyBridgeOptimizer{HiGHS.Optimizer}
with 0 variable bridges
with 0 constraint bridges
with 0 objective bridges
with inner model A HiGHS model with 0 columns and 0 rows.

julia> MOI.supports(model, MOI.ConstraintDualStart(), MOI.ConstraintIndex{MOI.VectorOfVariables,MOI.Nonnegatives})
true

julia> MOI.supports(model.model, MOI.ConstraintDualStart(), MOI.ConstraintIndex{MOI.VectorOfVariables,MOI.Nonnegatives})
false
```

Here's the offending code:
https://github.com/jump-dev/MathOptInterface.jl/blob/9a54ba742ed1f0dbe63f7548c3c960dcac1dc8c1/src/Bridges/bridge_optimizer.jl#L1218-L1234

It ends up calling 
https://github.com/jump-dev/MathOptInterface.jl/blob/9a54ba742ed1f0dbe63f7548c3c960dcac1dc8c1/src/Bridges/Constraint/scalarize.jl#L121-L127

which is only true if the inner optimizer also supports it.

**Comment by blegat** [comment]
Here is the fix for a similar problem with the slack bridge https://github.com/jump-dev/MathOptInterface.jl/pull/1383/files

**Comment by odow** [comment]
Yeah is it sufficient to just look at the inner optimizer? If so, why is #1383 still a draft?

**Comment by blegat** [comment]
Because it needs tests ^^

**Comment by odow** [comment]
I've opened a few PRs to fix these
 - [ ] #1580 
 - [ ] #1579
 - [ ] #1578 
 - [ ] #1577 
 - [ ] #1576 
 - [ ] #1575
 - [ ] #1574

I still have the following to go
 - [ ] geomean_to_relentr.jl
 - [ ] function_conversion.jl
 - [ ] det.jl

**Comment by odow** [comment]
Closing because this is now fixed. The IndicatorSOS1Bridge PR is different.
