### ISSUE TITLE
[docs/convention] VariablePrimal: what should solvers return when there is no solution?

### ISSUE THREAD

**Issue by dourouc05** [jump-dev/MathOptInterface.jl#1600]
When working on Chuffed.jl, I wondered what I should return for `VariablePrimal` when the model is infeasible. Currently, this is not documented (https://github.com/jump-dev/MathOptInterface.jl/blob/master/src/attributes.jl#L1188-L1195). 

Intuitively, two solutions make sense to me: either throw an appropriate exception (similarly to `InvalidCallbackUsage` or `OptimizeInProgress`) or return `nothing`.

**Comment by odow** [comment]
You're fine to return `NaN` or throw an error. People should only check `VariablePrimal` if `PrimalStatus` indicates a solution is present. This is purposefully undefined behavior because solvers do different things.

**Comment by dourouc05** [comment]
Would it be possible to state clearly in the docs that this is undefined behaviour? (Which is done for C and C++, for instance.) This could be useful for users when they encounter a mismatch between solvers and for solver implementers (mostly).

**Comment by odow** [comment]
> Would it be possible to state clearly in the docs that this is undefined behaviour?

Sure. Make a PR?
