### ISSUE TITLE
Unsupported attributes

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1614]
I think https://github.com/jump-dev/MathOptInterface.jl/pull/1613 should be reverted. The fallback of `set` is already throwing the expected error. Why was that PR needed?

**Comment by odow** [comment]
Because generic fallbacks get in the way. I'll find an example after the call today.

**Comment by odow** [comment]
Talked to @blegat offline. We can close this.

**Comment by blegat** [comment]
I understood https://github.com/jump-dev/MathOptInterface.jl/pull/1608 from our talk offline but I still don't understand https://github.com/jump-dev/MathOptInterface.jl/pull/1613.
Is it to make
https://github.com/jump-dev/MathOptInterface.jl/blob/2d76d9c8e1b2c6e77490dcc097acfca514b40315/src/Test/test_model.jl#L618-L621
work in the case where you have bridge-cache-optimizer layers ? Without this, I assume it just get set to the cache without error.

**Comment by odow** [comment]
#1613 is because some solvers, e.g., GLPK, call `MOI.Utilities.pass_attributes` in their `copy_to` implementations. It would be redundant for them to have to do a double loop to check for `supports`.

There's an issue I have been putting off until I work on JuMP: should a caching optimizer accept attributes and constraints that the optimizer doesn't support if the caching optimizer is in `EMPTY_OPTIMIZER`. We're a bit half-half on this front.

**Comment by blegat** [comment]
So this is a workaround because `MOI.set(::GLPK.Optimizer, ::UnsupportedAttribute, value)` does not throw the right error due to some dispatch issue with the fallback ? Why not fix `MOI.set(::GLPK.Optimizer, ::UnsupportedAttribute, value)` like it was done for the `AbstractBridgeOptimizer`?

**Comment by odow** [comment]
There are multiple ways we could have done it. What's so wrong about checking supports here?

**Comment by blegat** [comment]
If `MOI.set(::GLPK.Optimizer, ::UnsupportedAttribute, value)` is incorrect and it's passing the tests, then https://github.com/jump-dev/MathOptInterface.jl/pull/1613 is hiding the bug.
Assuming `MOI.set` is correctly implemented, there is no need for this support. We don't want to cover bugs.

**Comment by odow** [comment]
Fair point. I don't remember the detail, so I'll take another look.
