### ISSUE TITLE
Exclude nonconvex quadratic test

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1621]
Add an easy way to do 
https://github.com/jump-https://github.com/jump-dev/SCS.jl/blob/0f3806d55d83493574d1222f334b9c5a9ed19f95/test/MOI_wrapper.jl#L59-L65
in the Config

**Comment by odow** [comment]
We could add a check in 
https://github.com/jump-dev/MathOptInterface.jl/blob/2d76d9c8e1b2c6e77490dcc097acfca514b40315/src/Test/Test.jl#L248
for 
```Julia
ErrorException("Unable to transform a quadratic constraint into a second-order cone\nconstraint because the quadratic constraint is not strongly convex.\n\nConvex constraints that are not strongly convex (i.e., the matrix is\npositive semidefinite but not positive definite) are not supported\nyet.\n\nNote that a quadratic equality constraint is non-convex.")
```

**Comment by blegat** [comment]
In that case, we should probably create a custom error type that we throw in the bridge
