### ISSUE TITLE
Add SolverVersion <: AbstractOptimizerAttribute

### ISSUE THREAD

**Issue by jd-lara** [jump-dev/MathOptInterface.jl#1623]
Should the optimizer version be added to the [Optimizer attributes](https://jump.dev/MathOptInterface.jl/dev/reference/models/#Optimizer-attributes) ? 

Most solvers have a constant _SOLVER_VERSION defined in the package.

**Comment by odow** [comment]
Seems reasonable. Leaving breadcrumbs to `SolverName`, which is similar. 

https://github.com/jump-dev/MathOptInterface.jl/blob/2d76d9c8e1b2c6e77490dcc097acfca514b40315/src/attributes.jl#L708-L715

https://github.com/jump-dev/MathOptInterface.jl/blob/2d76d9c8e1b2c6e77490dcc097acfca514b40315/src/Test/test_attribute.jl#L98-L109

https://github.com/jump-dev/MathOptInterface.jl/blob/master/docs/src/reference/models.md#optimizer-attributes
