### ISSUE TITLE
Define supports for is_set_by_optimize attributes

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#1628]
`supports` is currently restricted to copyable attributes. But it would also be useful to extend the definition to optimizer attributes so you can know whether to query the attribute without risking an error.

We've discussed this before, but I can't find the issue. I think it may have been a comment on a pull request.

Related: https://github.com/jump-dev/JuMP.jl/pull/2704#discussion_r718030897

**Comment by odow** [comment]
I'm not convinced by this. I see it as too breaking because every solver will need to be updated.

**Comment by odow** [comment]
@blegat this is our remaining blocker.

**Comment by blegat** [comment]
Currently, we could require `supports` to be implemented and start testing it but not use it in `CachingOptimizer` yet. When we release v0.11 or v1.0, we start using it in `CachingOptimizer` in something like:
```julia
if has_fallback(attr) && !MOI.supports(model.optimizer, attr)
    return get_fallback(model, attr, ...)
else
    return MOI.get(model.optimizer, attr, ...)
end
```
For attributes such that `has_fallback` is false, it won't make any changes. So unless we test `MOI.supports` in the tests, the solvers won't notice the difference.

**Comment by odow** [comment]
I think the options are:

1. Do nothing. Release MOI v1.0 which is non-breaking compared with 0.10
2. Release a breaking v0.11 change with tests and updated code
3. Release a breaking v1.0 change with tests and updated code

I guess it's a pretty trivial update for authors upgrading to MOI 1.0 anyway; they just have to add `MOI.supports(::Optimizer, ::MOI.VariablePrimal, ::MOI.VariableIndex)` etc.

It's a bit annoying because there are other attributes like `ConstraintFunction` and `ConstraintSet` which are neither copyable or set by optimize.

**Comment by blegat** [comment]
For `ConstraintFunction`, it could be confusing since some solvers could support setting it but not getting it.

**Comment by odow** [comment]
Monthly call says: Don't add it, but document the reasons why, and the work-arounds.
