### ISSUE TITLE
Implement read! for LP file format

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#1675]
https://github.com/jump-dev/MathOptInterface.jl/blob/c34a59493ab84e1af9aed027ecf01b8a1630d371/src/FileFormats/LP/LP.jl#L289-L291

**Comment by odow** [comment]
There's an old implementation here that could be tidied up: https://github.com/odow/LPWriter.jl/blob/master/src/reader.jl

**Comment by guilhermebodin** [comment]
Hi, @odow I am giving it a try. Might open a PR this week.
