### ISSUE TITLE
Bridge request: number type conversion

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1694]
It was recently brought up on Gitter (both with @freemin7 on 29th of November, and with @chriscoey on 3rd of November).
We could define a bridge `NumberConversionBridge{T,S}` converting constraints with numbers of type `T` to `S`.
Then, the solver expecting constraints of type `S` would add `MOI.NumberConversionBridge{T,S}` in `MOI.ListOfNonstandardBridges{T}()`.

**Comment by odow** [comment]
This came up in https://github.com/jump-dev/MiniZinc.jl. I'd like to be able to use `MiniZinc.Optimizer{Int}(MiniZinc.Chuffed())` and have all coefficients converted to `Int`, and throw an appropriate error if they can't be converted. That would allow JuMP to start with `Float64` input data and pass to an MOI solver with a different number type.

**Comment by odow** [comment]
Is there still motivation for this? I think the conclusion from https://github.com/jump-dev/JuMP.jl/pull/3191 was that we should allow JuMP to pass things other than `Float64`.
