### ISSUE TITLE
JET check of MathOptInterface

### ISSUE THREAD

**Issue by goerch** [jump-dev/MathOptInterface.jl#1700]
Just FYI: [JET](https://github.com/aviatesk/JET.jl/)'s main branch is able to check `MathOptInterface`. An example report is [available](https://github.com/aviatesk/JET.jl/issues/223#issuecomment-986210896).

**Comment by odow** [comment]
Some of those look like easy fixes.

**Comment by odow** [comment]
Closing because it seems like JET isn't ready for prime-time yet: https://github.com/aviatesk/JET.jl/issues/289. It's something we can come back to in future once the package is more stable.
