### ISSUE TITLE
Error in LaTeX Output for Intervals

### ISSUE THREAD

**Issue by pedromxavier** [jump-dev/MathOptInterface.jl#1728]
When printing intervals with print option `MIME"text/latex"`, both enclosing brackets render as LaTeX errors.

![image](https://user-images.githubusercontent.com/31925649/152408861-f1732e32-a557-4137-af5f-9ada99928309.png)

**Comment by pedromxavier** [comment]
This is probably due to printing "\\[" and "\\]" instead of plain "[" ... "]" or "\\left[" ... "\\right]". Any ideia on which is better?

**Comment by odow** [comment]
Here's where we do the printing:
https://github.com/jump-dev/MathOptInterface.jl/blob/3f9b256d3c4767320306561b71986c465b3e2dbf/src/Utilities/print.jl#L298-L306
We probably just need to remove the `\\` and update any tests etc.
