### ISSUE TITLE
Add test for conic problem with constraints but no variables

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#1741]
See this issue in ECOS: https://github.com/jump-dev/ECOS.jl/issues/132#issuecomment-1039861056

We should see what happens for models of the form:
```Julia
model = MOI.Utilities.Model{Float64}()
f = MOI.VectorAffineFunction(MOI.VectorAffineTerm{Float64}[], [1.0, 0.5, 0.5])
MOI.add_constraint(model, f, MOI.SecondOrderCone(3))
```

<s>They might solve, or they might error, but they shouldn't segfault.</s>

Test for `MOI.OPTIMAL` or `MOI.INVALID_MODEL` as the termination status.

**Comment by blegat** [comment]
What about tests that add empty equality constraints like `test_linear_VectorAffineFunction_empty_row` and `test_conic_PositiveSemidefiniteConeTriangle` ?
CSDP and SDPT3 fail these tests. Currently they throw an error.
Should they not throw any error but return `INVALID_MODEL` instead and the test would accept that ?

**Comment by blegat** [comment]
DSDP also does not support problems with no constraints.
