### ISSUE TITLE
Constraint.RSOCtoPSDBridge fails for dimension 2

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1761]
The bridge transforms `(t, u, x)` from `2tu >= ||x||_2`, `t, u >= 0` to
```
t   x'
x   2uI
```
is PSD.
However, when the dimension is 2, i.e., the length of `x` is zero, this is transformed into the 1x1 PSD constraint `t >= 0`.
This is missing the constraint that `u` should be nonnegative.
Ideally the bridge should add two linear inequality constraints but in the meantime it should at least provide a nice error instead of being incorrect.

Detected while going from DeprecatedTest to Test in https://github.com/jump-dev/CSDP.jl/pull/72

**Comment by odow** [comment]
Does it make sense for a RSOC to have dimension 2? It came up here previously: https://github.com/jump-dev/MathOptInterface.jl/pull/1349

**Comment by blegat** [comment]
A SOC of dimension 2 is bridged into an RSOC of dimension 2 by the `Bridges.Constraint.SOCtoRSOC` bridge
