### ISSUE TITLE
Using `empty!` with `OptimizerWithAttributes`

### ISSUE THREAD

**Issue by xinkai-zhou** [jump-dev/MathOptInterface.jl#1765]
If I do `MOI.OptimizerWithAttributes(KNITRO.Optimizer, "algoritm"=> KNITRO.KN_ALG_BAR_DIRECT)`, and then use `MOI.empty!(optimizer)` before adding variables, I'd get `MethodError: no method matching empty!(::MathOptInterface.OptimizerWithAttributes)`.

**Comment by blegat** [comment]
You should first instanciate it with `MOI.instantiate`

**Comment by odow** [comment]
To clarify:
```Julia
constructor = MOI.OptimizerWithAttributes(KNITRO.Optimizer, "algoritm"=> KNITRO.KN_ALG_BAR_DIRECT)
model = MOI.instantiate(constructor)
```

In future, please post usage questions like this on the community forum: https://discourse.julialang.org/c/domain/opt/13

**Comment by xinkai-zhou** [comment]
I see, thank you both for clarifying!
