### ISSUE TITLE
Discover fixed excluded tests

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1770]
It would be useful to have a keyword argument to `runtests` that is unset by default but when set it would run excluded tests as well and throw warning when excluded tests now work.

**Comment by blegat** [comment]
I tried this, it does not seems as simple as I would expect, we cannot just play with `_error_handler` because it won't catch the errors occuring in `@test` macros and incorrect results.

**Comment by odow** [comment]
It's not that hard to swap the `exclude` for an `include` and see what happens.

**Comment by blegat** [comment]
That's a good trick indeed, just used that for https://github.com/jump-dev/MosekTools.jl/pull/98, you can easily see them in the Test Summary. Maybe we could add that in the doc
