### ISSUE TITLE
Test get DualObjectiveValue even if excluded

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1773]
It is not supported by OSQP even if it supports duals
https://github.com/jump-dev/MathOptInterface.jl/blob/f96f7cb7947af4546d0f1aa1d18c482024aaf9fc/src/Test/test_infeasibility_certificates.jl#L102
https://github.com/jump-dev/MathOptInterface.jl/blob/f96f7cb7947af4546d0f1aa1d18c482024aaf9fc/src/Test/test_infeasibility_certificates.jl#L164

**Comment by odow** [comment]
So what is the certificate returned by OSQP?

**Comment by odow** [comment]
Can OSQP not use: 
```Julia
function MOI.get(model::Optimizer, attr::MOI.DualObjectiveValue)
    MOI.check_result_index_bounds(model, attr)
    return MOI.Utilities.get_fallback(model, attr, Float64)
end
```

**Comment by blegat** [comment]
NO because it does not implement the needed getters, https://github.com/jump-dev/MathOptInterface.jl/issues/1759 would be a solution. But I think the tests should be fixed as well

**Comment by odow** [comment]
Just to exclude `DualObjectiveValue`? I assume that we want to test the infeasibility certificate we don't want to skip ConstraintDual as well?

**Comment by blegat** [comment]
Yes, just to exclude `DualObjectiveValue`, you don't skip `ConstraintDual`
