### ISSUE TITLE
promote not working

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1785]
```julia
julia> f = 1 * MOI.VariableIndex(1)
MathOptInterface.ScalarAffineFunction{Int64}(MathOptInterface.ScalarAffineTerm{Int64}[MathOptInterface.ScalarAffineTerm{Int64}(1, MathOptInterface.VariableIndex(1))], 0)

julia> g = 1.0 * f
MathOptInterface.ScalarAffineFunction{Float64}(MathOptInterface.ScalarAffineTerm{Float64}[MathOptInterface.ScalarAffineTerm{Float64}(1.0, MathOptInterface.VariableIndex(1))], 0.0)

julia> promote(f, g)
ERROR: promotion of types MathOptInterface.ScalarAffineFunction{Int64} and MathOptInterface.ScalarAffineFunction{Float64} failed to change any arguments
Stacktrace:
 [1] error(::String, ::String, ::String)
   @ Base ./error.jl:42
 [2] sametype_error(input::Tuple{MathOptInterface.ScalarAffineFunction{Int64}, MathOptInterface.ScalarAffineFunction{Float64}})
   @ Base ./promotion.jl:374
 [3] not_sametype(x::Tuple{MathOptInterface.ScalarAffineFunction{Int64}, MathOptInterface.ScalarAffineFunction{Float64}}, y::Tuple{MathOptInterface.ScalarAffineFunction{Int64}, MathOptInterface.ScalarAffineFunction{Float64}})
   @ Base ./promotion.jl:368
 [4] promote(x::MathOptInterface.ScalarAffineFunction{Int64}, y::MathOptInterface.ScalarAffineFunction{Float64})
   @ Base ./promotion.jl:351
 [5] top-level scope
   @ REPL[10]:1
```

**Comment by odow** [comment]
Did this ever work? In what context is it called? What should the return be? I think we want to be careful automatically promoting `{Int}` to `{Float64}`.

**Comment by blegat** [comment]
This came across when working on https://github.com/jump-dev/SumOfSquares.jl/pull/245/
I ended up doing https://github.com/jump-dev/SumOfSquares.jl/blob/6d93d0a231584d7026f9a5b1addb27f45437557f/docs/src/tutorials/Symmetry/cyclic.jl#L156 as a workaround.
I forgot exactly why it's needed, I'll post more details.

**Comment by odow** [comment]
@blegat, what do we need here now that JuMP has `model_convert` etc? It seems like we shouldn't be doing these conversions at the MOI level.

**Comment by blegat** [comment]
This is true, maybe `model_convert` fixes this now, I'll try it out in https://github.com/jump-dev/SumOfSquares.jl/pull/249

**Comment by odow** [comment]
What is the status of this?

**Comment by blegat** [comment]
Haven't had time to check yet

**Comment by odow** [comment]
@blegat should we just close this? I don't think we want to add it to MOI directly?

**Comment by blegat** [comment]
Let me take a look this week :)
