### ISSUE TITLE
Support standard conic form in FileFormats.SDPA

### ISSUE THREAD

**Issue by kocvara** [jump-dev/MathOptInterface.jl#1796]
Hello,

I was re-directed here from 

https://github.com/jump-dev/Dualization.jl/issues/134

The point is that when read_from_file reads an SDPA input file, it converts the SDP problem into a "dual" version with additional variables and linear qualities. This makes some solvers (Mosek) **very** inefficient for the generated model, while the original problem, as stored in the SDPA file would be much easier to solve. Example:
```julia
model = read_from_file("sdplib/theta1.dat-s")
set_optimizer(model, Mosek.Optimizer)
```
generates a model with
```
  Constraints            : 1275                     
  Scalar variables       : 104   
  Matrix variables       : 1     
```
while the original formulation would just have 
```
  Constraints            : 104             
  Scalar variables       : 0               
  Matrix variables       : 1     
```
This is contrary to Matlab/Yalmip treatment of SDPA files:
```julia
model = read_from_file("sdplib/thetaG11.dat-s")
````
gives the problem in format A and
```julia
dual_model = dualize(model)
```
in format B, while Matlab/Yalmip
```matlab
>> [con, obj] = loadsdpafile('../../../sdplib/thetaG11.dat-s');
```
gives format B and
```julia
[cond,objd,X,free] = dualize(con,obj)
```
gives format A.

**Comment by blegat** [comment]
It would be possible to add support for reading directly the standard form. The choice to read the SDPA into the geometric form was a bit arbitrary and we thought there is no need to implement both as we have Dualization and the Dualization step should be negligible compared to the solve time.
In any case, the reading would still be geometric form by default and standard form should be manually chosen. We won't automatically adapt the choice between standard or geometric form depending on the solver.
I'd like to check first whether the performance issue in Dualization could be fixed though.

**Comment by odow** [comment]
@blegat is this needed in light of the updates in Dualization?

**Comment by blegat** [comment]
I don't think it is now that the performance issue was fixed in Dualization

**Comment by kocvara** [comment]
Very fast after the update, thanks! Perhaps just one thing - the user could be made aware of the format read by read_from_file(?) .

**Comment by blegat** [comment]
Indeed, I choose the geometric conic form because it was the one specified in http://plato.asu.edu/ftp/sdpa_format.txt.
I explicited this choice in the docstring but it seems we forgot to include the docstring in the docs. Should be resolved by https://github.com/jump-dev/MathOptInterface.jl/pull/1797.
