### ISSUE TITLE
FileFormats.MPS: add option to not write OBJSENSE

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#1806]
Introduced in https://github.com/jump-dev/MathOptInterface.jl/pull/1391, but broke https://github.com/joaquimg/BilevelJuMP.jl/issues/170.

We should add an option to skip
https://github.com/jump-dev/MathOptInterface.jl/blob/6b50fa0f9e31ef97a06facaad60af7d0b6ae3d2a/src/FileFormats/MPS/MPS.jl#L174-L178
and negate the objective coefficients.

cc @joaquimg

**Comment by joaquimg** [comment]
If we want to be strict on writing, the default should be to skip that code.
