### ISSUE TITLE
FileFormats.NL: add reader

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#1811]
The blocker for an NL reader has been a suitable data structure to read it into. 

We should build on https://github.com/jump-dev/MathOptInterface.jl/pull/1804 and add a NL reader. This would be a boon to JuMP benchmarking.

**Comment by jd-foster** [comment]
Would this wrap ASL_jll (à la AMPLNLReader.jl)?

**Comment by odow** [comment]
No, we'd probably just try to parse the file in pure Julia.

**Comment by jd-foster** [comment]
Is this open to contributing it have you already got a draft?

**Comment by odow** [comment]
I haven't started on this. My guess is we initially just want to consider `read(io::IO)::Nonlinear.Model`, and then we can think about how to incorporate it into `MOI.FileFormats`.

**Comment by odow** [comment]
Did you make a start @jd-foster? Otherwise I'm going to do this.

**Comment by jd-foster** [comment]
No. Go for it.

**Comment by odow** [comment]
Okay, I tried a few things but it got delicate. I still don't have a clear design.

A couple of issues:
 * `write` wants a very particular model structure. It made sense to only implement `copy_to` so that we can deal with everything once, and not store additional copies of the model.
 * `read` wants to return model that we can copy into something else. That doesn't fit with `write`
 * `.sol` file parsing is annoying. Currently it [lives in AmplNLWriter](https://github.com/jump-dev/AmplNLWriter.jl/blob/e3292be1706f05e98e96e1c27a095df92afce543/src/AmplNLWriter.jl#L345-L472), but it relies on internal data of `MOI.NL.Model`, so it makes sense to move it here before refactoring `write`.

In particular, it's really annoying that the variable ordering in the NL file does not correspond to the ordering of variable indices in the MOI model!!! If binary/integer constraints were stored separately instead of depending on the order of variables, this would _greatly_ simplify things. But alas, that's no what happens.

Some options:
 * Keep everything the same and kludge `read` to store a model inside our current `Model`, then overload `get` for it. That would lead to problems because you couldn't ask for `get` if you copied a problem to `Model`, only if you called `read`. 
 * Make a new `Model` and have `write` create a second copy of the problem. This is probably the right way to go, but it breaks the assumptions in AmplNLWriter which currently has the sol file parsing.

**Comment by odow** [comment]
Closed by:
 * #1848 
 * #1846 
 * #1843 
 * #1842 
 * #1835
