### ISSUE TITLE
MOI.AbstractNLPEvaluator as a function or constraint container

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/MathOptInterface.jl#1814]
It is unclear from MOI.Test and from the doc whether the AbstractNLPEvaluator expression should contain the nonlinear expression or the non-linear constraint.
Given `l <= g(x) <= u`,
the oracle interface (Jacobian, Hessian) provides information on `g at a given x`. However, the two valid examples in `Test/test_nonlinear.jl`, `HS071` and `FeasibilitySenseEvaluator` have constraint_expr return the constraint expression `g(x) <= u`.

Having the bounds seem non-relevant since the BlockData API includes the bounds:
`MOI.NLPBlockData(MOI.NLPBoundsPair.(lb, ub), evaluator, true)`

**Comment by odow** [comment]
`constraint_expr` returns the full expression:
https://github.com/jump-dev/MathOptInterface.jl/blob/4d0f52e7eeebabc8ea87cc81ea3386ff8f6fa329/src/nlp.jl#L225-L236

It's something that in retrospect wasn't needed, but it's too late to change now.

**Comment by matbesancon** [comment]
OK I see, I had missed this docstring I was looking at the one of the types mostly. Do you prefer closing this or keeping it open for the NL redesign?

**Comment by odow** [comment]
Let's close it. It's already on my mental list of "things that could be done better"
