### ISSUE TITLE
Nonlinear: change how constraints are parsed

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#1817]
To minimize differences when refactoring, we kept the same parsing behavior as JuMP. That means, constraints like `x^2 <= 1` get parsed into `x^2 - 1 <= 0.0`:
https://github.com/jump-dev/MathOptInterface.jl/blob/1af7064cc77d9948a5f0d0a87a758d08c2f06c91/src/Nonlinear/parse.jl#L242-L259

Changing this behavior would lead to more informative RHSs being passed to the solvers, and remove an additional operation. However, doing so would break JuMP's tests and printing, which have things like this:
https://github.com/jump-dev/MathOptInterface.jl/blob/1af7064cc77d9948a5f0d0a87a758d08c2f06c91/test/Nonlinear/Nonlinear.jl#L296-L303

As suggested by @blegat https://github.com/jump-dev/MathOptInterface.jl/pull/1804#discussion_r857043127, one option is to remove the ability to specify constraints as `a <= b`, and instead force `add_constraint(model, f, set)`, and then make JuMP keep the existing behavior.

**Comment by blegat** [comment]
> constraints like `x^2 <= 1` get parsed into `x^2 - 1 <= 0.0`

That's the opposite right?

Tha's a good argument, we don't want MOI to have to do these choices. Everything is explicit in MOI

**Comment by odow** [comment]
> That's the opposite right?

No, at the moment that's what JuMP does.
