### ISSUE TITLE
Nonlinear clarify role of Nonlinear.Model vs MOI.NLPBlockData

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/MathOptInterface.jl#1823]
The two appear from the documentation as containers for the nonlinear parts of a model.

The difference seems to be that Model is iteratively constructed and then passed to the NLPBlockData which is not supposed to be modified anymore (since it doesn't have a add, delete API).

If the model can still be modified after adding the NLPBlockData, it means the Optimizer to which the NLPBlock is set should just hold onto the data but not process the nonlinear constraints yet and wait `MOI.optimize!` time for it (I don't think this is currently in the docs if that's the case)

**Comment by odow** [comment]
You should only create and pass NLPBlockData once everything has finished being constructed in Model. The docs could be clarified.
