### ISSUE TITLE
Unnecessary copy in MOI.modify?

### ISSUE THREAD

**Issue by haraldo85** [jump-dev/MathOptInterface.jl#1921]
We have noticed that changing objective and constraint coefficients seem to be slow due to the line 'terms = copy(terms)' in the MOIU._modifycoefficient function defined in MOI.Utilities.functions.jl. 

The copy seems unnecessary when used in the functions below
```
MOI.modify(
    o::MOIU.ObjectiveContainer,
    ::MOI.ObjectiveFunction,
    change::MOI.AbstractFunctionModification,
)

function MOI.modify(
    v::MOIU.VectorOfConstraints{F,S},
    ci::MOI.ConstraintIndex{F,S},
    change::MOI.AbstractFunctionModification,
) where {F,S}


For example, in the body of MOI.modify(
    o::MOIU.ObjectiveContainer,
    ::MOI.ObjectiveFunction,
    change::MOI.AbstractFunctionModification,
)
```
the MOIU._modifycoefficient function is used under the hood in the call to this line

o.scalar_affine = modify_function(o.scalar_affine, change)

which overwrites the first input anyway, so the copy of terms does not seem necessary.

By removing the copy in MOIU._modifycoefficient, we find that update time goes down from 3 sec to 0.3 sec in our test case, due to less allocation and GC.

**Comment by odow** [comment]
Do you have a reproducible example for the test-case?

**Comment by odow** [comment]
Ah, in this case we can omit the copy:
https://github.com/jump-dev/MathOptInterface.jl/blob/fc89aa4c3b35cfc4fdadd6769617060f8340cce9/src/Utilities/objective_container.jl#L168-L174
and here
https://github.com/jump-dev/MathOptInterface.jl/blob/fc89aa4c3b35cfc4fdadd6769617060f8340cce9/src/Utilities/vector_of_constraints.jl#L160-L166

We should probably add allow a modify keyword to `modify_function`.
