### ISSUE TITLE
Support format from QPLib

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/MathOptInterface.jl#1972]
I don't think any of the formats histed on QPLib are supported by MOI at the moment.
https://qplib.zib.de/
One is a modified .lp
```julia
julia> src = MOI.FileFormats.Model(filename="QPLIB_3913.lp")
       MOI.read_from_file(src, joinpath(@__DIR__, "QPLIB_3913.lp"))
ERROR: Name contains with invalid character: b2^2
```

The QPLib seems to be a homebrew but I couldn't find any specification for it and not sure it is used beyond storing instances on there.
Ping @ambros-gleixner in case for this one

**Comment by odow** [comment]
Specification is in the appendix of http://www.optimization-online.org/DB_FILE/2017/02/5846.pdf

**Comment by odow** [comment]
I don't know if we need to explicitly support the qplib format. Is it used anywhere else? We support quadratic MPS, and https://github.com/jump-dev/MathOptInterface.jl/pull/1974 adds support for quadratic LP.

**Comment by odow** [comment]
Closing because I don't think we need explicit QPLib support now that we have #1973. Although if the LP reader is too slow, perhaps we can revisit.
