### ISSUE TITLE
FileFormats.LP: support quadratic functions

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#1973]
Goes with #1972. 

I took a read of the different docs:

CPLEX: https://www.ibm.com/docs/en/icos/12.9.0?topic=representation-quadratic-terms-in-lp-file-format
Gurobi: https://www.gurobi.com/documentation/9.5/refman/lp_format.html
Mosek: https://docs.mosek.com/latest/pythonfusion/lp-format.html

 * Quadratic terms are enclosed in `[ ] / 2`
 * CPLEX and Gurobi don't include the `/ 2` in constraints
 * We should support `x * x` and `x^2`, but when writing, always use `^`

**Comment by matbesancon** [comment]
> We should support x * x and x^2, but when writing, always use ^

why this one? ScalarQuadraticTerm will store the two variables anyway, is `x^2` easier for the writer?

**Comment by odow** [comment]
Writing `x^2` seems like the default for Gurobi and CPLEX. But they can read both.
