### ISSUE TITLE
Implement `isless(::VI, ::VI)`?

### ISSUE THREAD

**Issue by pedromxavier** [jump-dev/MathOptInterface.jl#1985]
In some of the projects I am running it is necessary, sometimes, to sort variables by their indices.

Instead of just entering
```julia
isless(x::MOI.VariableIndex, y::MOI.VariableIndex) = isless(x.value, y.value)
```
I came up with a construct more like
```julia
varcmp(x::V, y::V) where V = isless(x, y)
varcmp(x::MOI.VariableIndex, y::MOI.VariableIndex) = isless(x.value, y.value)
```
in order to avoid *type piracy*.

I was wondering if, since `==`  is implemented, then implementing `<` also would be desirable.
The first already assumes no ambiguity between comparing *variable indices* and *variable's values*.

**Comment by odow** [comment]
You can use the `by` argument of `sort`:
```julia
x = MOI.VariableIndex.(rand(Int, 10))
sort(x; by = xi -> xi.value)
```

We won't be adding comparison methods because it's too easy for people to get confused with `x <= y` being on the index, not the value.

**Comment by pedromxavier** [comment]
It breaks down when using some tools that rely on calling `<` over arbitray types used to represent variables.
It works for variables represented using `Symbol`, `Int`, `String` etc...

**Comment by odow** [comment]
Do you have a larger example where this is needed?

**Comment by pedromxavier** [comment]
An important step during QUBO reformulation (ToQUBO.jl) is to quadratize binary polynomials. There is code for doing this that must pick variables in order to avoid redundancy during degree reduction. If `<` was available for index comparison, simply parametrizing the PBF struct as `PBF{VI, Float64}` makes integration automatic.

Also, it is useful when build variable mappings between model reformulations in this context.

**Comment by odow** [comment]
But are you using `sort` or something else?

**Comment by pedromxavier** [comment]
There are calls to `sort` and `minimum` but also to `<` directly.

**Comment by odow** [comment]
I think it's just fundamentally wrong to compare `x <= y` when it comes to variables; they don't have an ordering.

Whereas `x == y` (and `isequal`, etc.) is a well-defined thing, and is needed for things like `x in list` or `haskey(dict, x)`.

So I think you need to use some wrapper type or some indirection like `varcmp`.

**Comment by pedromxavier** [comment]
IMO, there is a well-defined ordering for any `<:Index`, including constraint indices as well.

Using some cycle avoidance rules during simplex, for example, makes me think that comparing indicies (not the variables themselves) is a very natural thing to do.

If this is not making its way into MOI, I will stick to the proxy approach. Otherwise I'd be happy to submit a PR.
Anyways, I had to give it a try and ask this question before adding a few bits of indirection to those codebases.

**Comment by odow** [comment]
> IMO, there is a well-defined ordering for any <:Index, including constraint indices as well.

The `.value` field is an implementation detail. There is no guarantee that `value = 1` was added before `value = 2`, or even that the values need to be 1-indexed and positive (some bridges return negative values, for example).

So a sort would give you _an_ ordering, but it isn't necessarily what one would expect.

Can you point to code where this is used?

**Comment by pedromxavier** [comment]
Sure,

`sort`: (`varcmp` in action)
https://github.com/psrenergy/ToQUBO.jl/blob/ea6f694c75f78f4e1bcd0df5a91bc301ff9a9afd/src/pbo/quadratization.jl#L91
https://github.com/psrenergy/ToQUBO.jl/blob/ea6f694c75f78f4e1bcd0df5a91bc301ff9a9afd/src/pbo/tools.jl#L54
https://github.com/psrenergy/ToQUBO.jl/blob/ea6f694c75f78f4e1bcd0df5a91bc301ff9a9afd/src/pbo/print.jl#L6

`<`:
https://github.com/psrenergy/QUBOTools.jl/blob/7eb5a73debe28c4bfebba87b33d812834f43c5b6/src/library/tools.jl#L137

As in the example I mentioned before (Bland's rule), any ordering suffices as long as indices are unique.

**Comment by pedromxavier** [comment]
In both cases, this was the only difficulty in writing generic code with a parametric type `V` for variables that could be automaticaly plugged into MOI by chosing `V = VI`.
We have chosen to keep things decoupled from the interface in order to keep subpackages lightweight.

**Comment by odow** [comment]
I'll add this to the discussion on tomorrow's developer call.

**Comment by odow** [comment]
We discussed this on today's call. The conclusion was that variables don't have a total ordering because the `value` field is arbitrary; solvers can add variables with the `.value` field in any order, including non-monotonic and with holes, so long as the indices are unique.

The suggestion is to keep using the custom `varcmp` comparison function. 

Closing as won't-fix.

**Comment by pedromxavier** [comment]
Thanks for taking this further @odow, knowing this was all I needed to keep going.
About gitter, I will surely get involved soon. I've registered and with a single look I've already seen some familiar faces 😄.
