### ISSUE TITLE
[Nonlinear] Add support for more functions

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#1996]
@harshangrjn says that there are a bunch of functions in MINLPlib that AMPL supports that JuMP currently doesn't.

Some of them are listed here:
https://github.com/jump-dev/MathOptInterface.jl/blob/2aba5d5450b3a5931ff557cb8969efc2987b3ffd/src/FileFormats/NL/NLExpr.jl#L30-L101
We should go through and reconsider the ones we've left out.

In addition, Harsha says he will link to a list of functions that he'd like added.

**Comment by odow** [comment]
GAMS has a bunch here: https://www.gams.com/latest/docs/UG_Parameters.html

The univariate functions supported by JuMP/MOI are here:
https://github.com/jump-dev/MathOptInterface.jl/blob/2aba5d5450b3a5931ff557cb8969efc2987b3ffd/src/Nonlinear/univariate_expressions.jl#L12-L83
the multivariate functions are here:
https://github.com/jump-dev/MathOptInterface.jl/blob/2aba5d5450b3a5931ff557cb8969efc2987b3ffd/src/Nonlinear/operators.jl#L531-L547

A missing one that people use quite a bit is `sign` (@ccoffrin has an example where this needs to be a registered function)

**Comment by harshangrjn** [comment]
`signpower(x, p)` -> `sign(x) * abs(x)^p` for any real `p > 1` 

A few examples where this nonlinearity appears: 
1. https://www.minlplib.org/gastransnlp.html ([JuMP model](https://github.com/lanl-ansi/MINLPLib.jl/blob/cca5d2f69fb04814cf1fdaf99e67ee2ce2050400/instances/minlp2/gastransnlp.jl)) 
2. https://www.minlplib.org/waternd_fosspoly0.html ([JuMP model](https://github.com/lanl-ansi/MINLPLib.jl/blob/cca5d2f69fb04814cf1fdaf99e67ee2ce2050400/instances/minlp2/waternd_fosspoly0.jl))

**Comment by odow** [comment]
Ah. There's in the GAMS format, not AMPL. We have an open question then, of whether to bring in modeling functions like `signpower` that exist only in GAMS, and are not Julia functions. (Although I guess we could define `MOI.Nonlinear.signpower`.)

**Comment by harshangrjn** [comment]
Assuming `sign` and `abs` functions will be internally supported, writing `signpower` as an explicit constraint by the user shouldn't be too much though.

**Comment by odow** [comment]
I guess the issue is that `signpower` is smooth and differentiable at `x=0`. Whereas `sign(x)` and `abs(x)` are not.

**Comment by odow** [comment]
We've added a few missing functions like `atan`, `min`, and `max`. But I'm not sure we want to add `signpower` etc. The main reason is that AMPL doesn't support them, and that's our main expression-tree driven interface to Ipopt, etc. There's also the problem that they aren't functions in Julia.

**Comment by harshangrjn** [comment]
With `ifelse(x > 0, x^p, -(-x)^p)`, an issue could be that the variable `x` could be anywhere in `[-U,U]` (`U > 0`). Apriori it is not known within JuMP unless the optimization model is solved. So it could result in something like say `-(-2)^1.5`, which is undefined in real values. Signpower isn't as important as few other functions. So, this can be easily reformulated by the user before creating the model.

**Comment by odow** [comment]
Oh. I guess I forgot `ifelse` eagerly evaluates both arguments. This is a Julia problem, not an AMPL problem:
```julia
julia> using JuMP, AmplNLWriter, Ipopt_jll

julia> p = 1.5
1.5

julia> model = Model() do
           return AmplNLWriter.Optimizer(Ipopt_jll.amplexe)
       end
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: AmplNLWriter

julia> @variable(model, -10 <= x <= 10, start = 1.0)
x

julia> @NLobjective(model, Min, ifelse(x > 0, x^p, -(-x)^p))

julia> optimize!(model)
Ipopt 3.14.4: 

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit https://github.com/coin-or/Ipopt
******************************************************************************

This is Ipopt version 3.14.4, running with linear solver MUMPS 5.4.1.

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        1

Total number of variables............................:        1
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        1
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.0000000e+00 0.00e+00 1.50e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1 -4.3911148e-01 0.00e+00 8.71e-01  -1.0 1.58e+00    -  8.50e-01 1.00e+00f  1
   2 -3.1176893e+01 0.00e+00 4.24e+00  -1.0 2.60e+01   0.0 3.94e-01 3.59e-01f  1
   3 -3.1397342e+01 0.00e+00 1.70e-01  -1.0 7.60e-01    -  1.00e+00 6.14e-02f  2
   4 -3.1595906e+01 0.00e+00 1.05e-05  -1.7 4.19e-02    -  1.00e+00 1.00e+00f  1
   5 -3.1622629e+01 0.00e+00 1.88e-07  -3.8 5.63e-03    -  1.00e+00 1.00e+00f  1
   6 -3.1622775e+01 0.00e+00 5.67e-12  -5.7 3.09e-05    -  1.00e+00 1.00e+00f  1
   7 -3.1622777e+01 0.00e+00 7.23e-16  -8.6 3.88e-07    -  1.00e+00 1.00e+00f  1

Number of Iterations....: 7

                                   (scaled)                 (unscaled)
Objective...............:  -3.1622777073519540e+01   -3.1622777073519540e+01
Dual infeasibility......:   7.2277457708574397e-16    7.2277457708574397e-16
Constraint violation....:   0.0000000000000000e+00    0.0000000000000000e+00
Variable bound violation:   9.9471709091858429e-08    9.9471709091858429e-08
Complementarity.........:   2.5059009350611340e-09    2.5059009350611340e-09
Overall NLP error.......:   2.5059009350611340e-09    2.5059009350611340e-09


Number of objective function evaluations             = 13
Number of objective gradient evaluations             = 8
Number of equality constraint evaluations            = 0
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 0
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 7
Total seconds in IPOPT                               = 0.005

EXIT: Optimal Solution Found.

julia> solution_summary(model)
* Solver : AmplNLWriter

* Status
  Termination status : OTHER_ERROR
  Primal status      : NO_SOLUTION
  Dual status        : NO_SOLUTION
  Message from the solver:
  "Error calling the solver. Failed with: DomainError(-10.000000099471709, "Exponentiation yielding a complex result requires a complex argument.\nReplace x^y with (x+0im)^y, Complex(x)^y, or similar.")"

* Candidate solution

* Work counters
  Solve time (sec)   : 5.39739e-02
```

**Comment by odow** [comment]
This `ifelse` domain errors are fixed here: https://github.com/jump-dev/MathOptInterface.jl/pull/2050

**Comment by odow** [comment]
> Signpower isn't as important as few other functions

Like what?

**Comment by odow** [comment]
Talked to @ccoffrin: we're in favor of closing this. A good rule for adding support is "is it supported both by Base Julia _and_ AMPL's ASL?"
