### ISSUE TITLE
FileFormats.MPS: Read/Write conic constraints from MPS files

### ISSUE THREAD

**Issue by yuwenchen95** [jump-dev/MathOptInterface.jl#2013]
Hi. I'm trying to read SOC constraints from MPS files, i.e. "CSECTION" part [in this page](https://docs.mosek.com/10.0/capi/mps-format.html) , but find no support for it so far. Wish the package could add it later on.

**Comment by odow** [comment]
SOC constraints in MPS files are a MOSEK-specific extension which is why they're not currently implemented. I guess it makes sense to be able to read them, but writing is a little more unsure. 

For problems with SOC constraints, you could use the CBF format instead?

**Comment by yuwenchen95** [comment]
Thanks for your suggestion! I found the same examples inside CBLIB.
