### ISSUE TITLE
FileFormats.MPS OBJSENSE

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/MathOptInterface.jl#2015]
I have a model like the following:
```
NAME          model
OBJSENSE
  MIN
ROWS
 N  Obj 
 L  c1 
```

it seems the MPS parser does not support the OBJSENSE and sense on two different lines (or the OBJSENSE altogether?)
For what it's worth, the Wikipedia entry has this specification

**Comment by odow** [comment]
> the Wikipedia entry has this specification

😢 I hate MPS.

**Comment by matbesancon** [comment]
One day we'll unify them all :ring:
