### ISSUE TITLE
copy_to ignoring name because of too strict supports requirements

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/MathOptInterface.jl#2027]
I can't find where this is documented but IIRC VariableName should be `MOI.support`-ed only if
`get(model::ModelLike, ::Type{VariableIndex}, name::String)` is implemented.

However setting and getting variable names might still be okay. In this case copy_to ignored variable names in pass_attributes:

```julia
        if !MOI.supports(dest, attr, MOI.VariableIndex)
            if attr == MOI.VariableName() || attr == MOI.VariablePrimalStart()
                continue  # Skipping names and start values is okay.
            end
        end
```

the supports requirements seem too strict compared to the requirement of setting and getting names

**Comment by odow** [comment]
> I can't find where this is documented but IIRC VariableName should be MOI.support-ed only if
get(model::ModelLike, ::Type{VariableIndex}, name::String) is implemented.

I don't know if we've ever made that distinction. What solver do you have in mind? But I would assume that yes, if you want to add names you must also support retrieving them.

**Comment by matbesancon** [comment]
> if you want to add names you must also support retrieving them

this is not about retrieving names but retrieving variables from names. I think this is currently not possible in HiGHS?

**Comment by odow** [comment]
> I think this is currently not possible in HiGHS?

It is. See:

https://github.com/jump-dev/HiGHS.jl/blob/a789aaddffe2c9a5458a4538e0141d9f1e464872/src/MOI_wrapper.jl#L678-L690

**Comment by matbesancon** [comment]
In that case I am not sure what is happening here:
```julia

julia> optimizer = HiGHS.Optimizer()
A HiGHS model with 0 columns and 0 rows.

julia> file_model = MOI.FileFormats.Model(filename=file)
A Mathematical Programming System (MPS) model

julia> MOI.read_from_file(file_model, file)

julia> index_map = MOI.copy_to(optimizer, file_model)

julia> MOI.get(file_model, MOI.VariableName(), MOI.VariableIndex(1))
"C0001"

julia> MOI.get(optimizer, MOI.VariableName(), MOI.VariableIndex(1))
""

```

**Comment by odow** [comment]
What is `print(optimizer)` and `index_map[MOI.VariableIndex(1)]`?

**Comment by matbesancon** [comment]
```
julia> index_map[MOI.VariableIndex(1)]
MathOptInterface.VariableIndex(1)
```

Print optimizer is gigantic here and uses generic variable names:
```
0.0 + 1.0 v[494] + 11.21 v[994] >= 0.0
 0.0 + 1.0 v[495] + 33.6 v[995] >= 0.0
 0.0 + 1.0 v[496] + 1.15 v[996] >= 0.0
 0.0 + 1.0 v[497] + 3.19 v[997] >= 0.0
 0.0 + 1.0 v[498] + 1.35 v[998] >= 0.0
 0.0 + 1.0 v[499] + 3.06 v[999] >= 0.0
 0.0 + 1.0 v[500] + 11.73 v[1000] >= 0.0
```

**Comment by odow** [comment]
Lololololol: spot the mistake:

https://github.com/jump-dev/HiGHS.jl/blob/a789aaddffe2c9a5458a4538e0141d9f1e464872/src/MOI_wrapper.jl#L2189

I'll fix and add a proper test.

**Comment by odow** [comment]
Is this issue just for HiGHS in particular (in which case, we can move to HiGHS.jl), or the issue more broadly (in which case, we can keep open)?
