### ISSUE TITLE
write_to_file and read_from_file fallbacks

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/MathOptInterface.jl#2028]
Everytime I need to read/write from files I end up copy-pasting from the MOI.FileFormats documentation, could we add:

```julia
function MOI.write_to_file(src::MOI.ModelLike, file)
    dest = MOI.FileFormats.Model(filename=file)
    MOI.copy_to(dest, src)
    MOI.write_to_file(dest, file)
end
```

and 

```julia
function MOI.read_from_file(dest::MOI.ModelLike, file)
    src = MOI.FileFormats.Model(filename=file)
    MOI.copy_to(dest, src)
    # assuming here the indices map would not be needed
    return nothing
end
```

**Comment by odow** [comment]
This seems reasonable. I think we just avoided doing so as a historical artifact. Here are the methods to implement:

https://github.com/jump-dev/MathOptInterface.jl/blob/3c37f1d0695e84a5fcb1ea28f48856835e2e0ec9/src/MathOptInterface.jl#L118-L142
