### ISSUE TITLE
Implement Utilities.distance_to_set for more sets

### ISSUE THREAD

**Issue by freemin7** [jump-dev/MathOptInterface.jl#2033]
**Is your feature request related to a problem? Please describe.**
I have a model which contains a MathOptInterface.PowerCone and want to verify a the primal feasibility of a point.

**Describe the solution you'd like**
Support feasibility checking of all standard sets maintained by jump-dev. Short term i need a workaround.

**Describe alternatives you've considered**
I considered monkey-patching `_distance_to_set(var::Vector{Float64},cone::MathOptInterface.PowerCone) = distance_to_set(var::Vector{Float64},cone::MathOptInterface.PowerCone)` from MathOptSetDistances by @matbesancon however that did not work.

**Comment by odow** [comment]
Assuming we merge #2048, what distance would we use for this?

MOSD uses:

https://github.com/matbesancon/MathOptSetDistances.jl/blob/a449c4b178855db0b461d1aa13d60a5ae81b0eac/src/distance_sets.jl#L171-L185

**Comment by freemin7** [comment]
I think we established that what distance is used doesn't matter for the sake of feasibility checking as long as it implies the same [discrete metric](https://mathworld.wolfram.com/DiscreteMetric.html). 
Since i am not aware of any code base which depends on something else than the discrete metric pick and since this was "broken" before for those cones no code should change by the decision. I'd suggest we pick whatever is cheapest to compute and document what was used and that we guarantee that under <=0 it satisfies discrete metric. Should different features be required in the future by a code base this decision can be revisited in light of more information and multiple dispatch on what kind the user wants.

**Comment by odow** [comment]
@matbesancon what are your thoughts on this? We could potentially add MathOptSetDistances as a pkg extension?

**Comment by matbesancon** [comment]
yes that makes sense. The current dependencies are:
```
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
```

**Comment by matbesancon** [comment]
one of the key things to use these functionalities in solvers would be an in-place version of the projection to set

**Comment by blegat** [comment]
Not sure it should be a Pkg extension with these extensions, it's weird to have to import `StaticArrays` to be able to project your sets ^^
For the in-place version, totally agree, implementing in-place version with `MA.buffer_for` and `MA.operate!` would make this usable in solvers.

**Comment by matbesancon** [comment]
the other big functionality of SetDistances is the implementation of ChainRules for the projection gradient. Maybe this can be a separate extension

**Comment by odow** [comment]
> it's weird to have to import StaticArrays to be able to project your sets

What does this have to do with it? You'd need `using MathOptInterface, MathOptSetDistances`

**Comment by odow** [comment]
I meant add a `MathOptInterfaceMathOptSetDistances.jl` extension which linked up the `distance_to_set` functions.

**Comment by matbesancon** [comment]
and StaticArrays is lightweight enough to bring along, no?

**Comment by odow** [comment]
I don't understand what `StaticArrays` has to do with this. It wouldn't become a direct dependency of MOI. We'd add a package extension between MOI and MOSD.

**Comment by odow** [comment]
The extension would be:
```Julia
module MathOptInterfaceMathOptSetDistances
import MathOptInterface as MOI
import MathOptSetDistances as MOSD
MOI.distance_to_set(x, s) = MOSD.distance_to_set(MOSD .DefaultDistance(), x, s)
end
```
That's all. It avoids type-piracy in MOSD, and it avoids MOI having to re-implement everything.

**Comment by freemin7** [comment]
The name is a tad annoying. I hope no user has to type that.

**Comment by odow** [comment]
> The name is a tad annoying

What name? `MathOptInterfaceMathOptSetDistancesExt`? No. This would become a package extension like 
 * https://github.com/jump-dev/JuMP.jl/blob/master/ext/JuMPDimensionalDataExt.jl
 * https://jump.dev/JuMP.jl/stable/extensions/DimensionalData/

**Comment by blegat** [comment]
For which set is `distance_to_set` implemented in MOSD but not in MOI ? From a quick look, I don't see any

**Comment by blegat** [comment]
Indeed, I think it's simpler to move them to MOI rather than having a package extension.
