### ISSUE TITLE
Document two-arg version of `optimize!`

### ISSUE THREAD

**Issue by metab0t** [jump-dev/MathOptInterface.jl#2073]
There is a two-arg version of [`optimize!`](https://github.com/jump-dev/MathOptInterface.jl/blob/60709256ab029656f1ad0466e93aadff7928d8b2/src/MathOptInterface.jl#L84) that is not documented.
It is used in SCS.jl to implement a one-shot optimizer, so maybe it should be mentioned in https://jump.dev/MathOptInterface.jl/stable/tutorials/implementing/ ?

**Comment by odow** [comment]
It was added here: https://github.com/jump-dev/MathOptInterface.jl/pull/1592

The main reason we didn't document it more thoroughly at the time was: 
https://github.com/jump-dev/MathOptInterface.jl/blob/60709256ab029656f1ad0466e93aadff7928d8b2/src/MathOptInterface.jl#L66-L68

but I guess we're locked in now.

**Comment by metab0t** [comment]
Thanks!
The approach SCS.jl takes to acquire the matrix form via `MOI.Utilities.GenericModel` is quite neat.

**Comment by odow** [comment]
Yeah there's quite a lot of machinery sitting in `MOI.Utilities` to simplify the process now.
