### ISSUE TITLE
Open interval test for Rational

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#2134]
CDDLib is failing because of the open_interval test.
It runs these tests with the bounds
```julia
julia> typemin(Rational{BigInt})
-1//0

julia> typemax(Rational{BigInt})
1//0
```
but in the interval bridge, we just add them as bounds instead of ignoring them since we only do that for `AbstractFloat`.
We should do something in the bridge in case `isfinite` is false and it's not `AbstractFloat`.
This depends on whether we accept `1/0`, `2/0`, ... to denote `+Inf`:
```julia
julia> 1//0 > 0
true

julia> 1//0 < 0
false

julia> -1//0 < 0
true

julia> -1//0 > 0
false
```
It seems, the equality with `typemax` also works for rational:
```julia
julia> 1 // 0 == typemax(Rational{Int})
true

julia> 2 // 0 == typemax(Rational{Int})
true
```

**Comment by odow** [comment]
To clarify, this is a problem with the SplitIntervalBridge?

**Comment by blegat** [comment]
It is also a problem with the `Interval` set, how do we interpret a bound `1//0` ?

https://github.com/jump-dev/MathOptInterface.jl/blob/72dbc0a012cc0db5467116d837f6e86ac9c173e0/src/sets.jl#L271-L272

According to
```julia
julia> convert(Rational{Int}, Inf)
1//0

julia> convert(Rational{Int}, -Inf)
-1//0
```
we could say that it's indeed already clear in the doc so then it's just an issue with the bridge yes
