### ISSUE TITLE
rename ListOfConstraints?

### ISSUE THREAD

**Issue by mlubin** [jump-dev/MathOptInterface.jl#214]
https://github.com/JuliaOpt/MathOptInterface.jl/issues/203#issuecomment-364592475

@tkoolen

**Comment by odow** [comment]
I second this. But, should it return a list of all of the constraint types the model supports, regardless of how many constraints there in the model? 

This would be useful in https://github.com/JuliaOpt/MathOptInterface.jl/pull/354 to check that we test all of the supported constraints.
