### ISSUE TITLE
Bug in HermitianToSymmetricPSDBridge

### ISSUE THREAD

**Issue by araujoms** [jump-dev/MathOptInterface.jl#2170]
Some recent change, probably in JuMP 1.10 or 1.11, made the Hermitian PSD bridge stop working. Now an SDP that needs those constraints returns variables that are not necessarily PSD, and usually gives the wrong answer. The exception is of course Hypatia, as it doesn't use the bridge, but instead implements the Hermitian PSD cone natively.

An example code to see the issue is the state discrimination code I have posted many times before. It only shows up if d=3 or larger. Often the discrepancy between the value returned by the SDP and the analytical answer is small and the eigenvalues are non-negative, so you should try it a couple of times to see a big difference.
```julia
function random_state(d)
	x = randn(ComplexF64, (d,d))
	y = x*x'
	rho = Hermitian(y/tr(y))
	return rho
end


function discriminate(d)
#    model = Model(Hypatia.Optimizer)
    model = Model(SCS.Optimizer)
    
    rho1 = random_state(d)
    rho2 = random_state(d)
    E1 = @variable(model, [1:d, 1:d] in HermitianPSDCone())
    E2 = @variable(model, [1:d, 1:d] in HermitianPSDCone())
    @constraint(model, E1+E2 == I)
    obj = real(dot(rho1,E1) + dot(rho2,E2))/2
    @objective(model, Max, obj)
    optimize!(model)
    println(value(obj))

	#we print the analytical answer as well for debugging
    println(0.5 + 0.25*sum(svdvals(rho1-rho2)))

    #the eigenvalues are not always non-negative
    display(eigvals(value.(E1)))
    display(eigvals(value.(E2)))
end
```

**Comment by odow** [comment]
looking into this. It looks like a permutation issue. 

Our single test case wasn't very comprehensive:
https://github.com/jump-dev/MathOptInterface.jl/blob/54f2c48715229e17e430d3f06c11d92f9d190f6c/test/Bridges/Constraint/hermitian.jl#L24-L37
