### ISSUE TITLE
x86 frequently fails in CI

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#2183]
Various PRs #2179 #2182 have triggered this StackOverflow on 32-bit. I've tried both Julia 1.6 and 1.9. 

<img width="1035" alt="image" src="https://github.com/jump-dev/MathOptInterface.jl/assets/8177701/92291e74-ed33-427d-8dd8-4d88d0c3a893">

**Comment by odow** [comment]
Here's a different one

<img width="1064" alt="image" src="https://github.com/jump-dev/MathOptInterface.jl/assets/8177701/9ed83b18-0770-4d0a-a11e-288cefb322bb">

**Comment by odow** [comment]
I think this settles it

<img width="1064" alt="image" src="https://github.com/jump-dev/MathOptInterface.jl/assets/8177701/31a86fcc-efb5-4337-949a-3b068bfb08b3">

**Comment by blegat** [comment]
Why does the testset make such a difference

**Comment by odow** [comment]
I haven't seen this fail recently, so I'm going to close. We can always re-open.
