### ISSUE TITLE
More flexible AD

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#2193]
It would be nice to have an interface to get gradient/jacobian, hessian of arbitrary functions. At the moment, the interface is tailored to Ipopt which is like
```julia
min f(x)
s.t. g(x) in [lb, ub]
```
where `g` is a vector of nonlinear functions and `[lb, ub]` is a box.
So the interface can give the gradient of `f` and the jacobian of `g` but for https://github.com/blegat/SeqOpt.jl for instance, I would rather have the problem in that format:
```julia
min f(x)
s.t. g_i(x) in S_i
```
and would like to get the gradient/jacobian of each `g_i` separately.

We could have an like `eval_variable(::Function, ::ScalarNonlinearFunction)` but also for gradient.
That would be inefficient of course since we need to build the AD backend at every call and the AD backend is not even specified.
So I undestand we would need to kind of specify in advance what we will want to as AD features, build some NLP model with a tailored AD tape and then get efficient callbacks from that.
Being able to parametrize this AD backend like `MOI.Utilities.Model` would be ideal. So Ipopt will say that it want a `ScalarNonlinearFunction` objective and all constraints concatenated into a `VectorNonlinearFunction`-in-`Box` with a macro like `MOI.Nonlinear.@model(...)`.
I'm not saying we should go all the way to a macro like that but it would be nice to move into that direction a bit :)

**Comment by odow** [comment]
So the current trick is to build one `NLPEvaluator` with arbitrary box bounds. And then you can use that. It's what I did for https://github.com/chkwon/PATHSolver.jl/pull/82.

We could probably add a mechanism for querying the gradient of a single constraint. We recently added Hessian support: https://github.com/jump-dev/MathOptInterface.jl/pull/2162

**Comment by blegat** [comment]
Indeed, one `NLPEvaluator` for each constraint would do the trick. It's a good temporary solution but I guess it would be less efficient (e.g., if there are share sub-expressions) ?

> We could probably add a mechanism for querying the gradient of a single constraint. We recently added Hessian support: https://github.com/jump-dev/MathOptInterface.jl/pull/2162

It's unclear how to do this since the evaluator works by creating a sparse structure for the whole list of constraints so it will not be that efficient to get a sparse gradient. Maybe a dense gradient would be easy with some `searchsortedfirst`.

**Comment by odow** [comment]
> Indeed, one NLPEvaluator for each constraint

No, inside the model you create one NLPEvaluator that contains all of the constraints.

**Comment by frapac** [comment]
How about using transpose-Jacobian-vector product to evaluate the gradient of a single constraint? If we set a vector `v = (1, 0, ..., 0)` we get the gradient of the first constraint when evaluating `J' v` . However, we should make sure the routine takes into account the fact that most values in `v` are equal to 0 to save some work.

**Comment by odow** [comment]
> That doesn't work so well then because you get the full jacobian instead of one gradient for each constraint

I proposed that we add an additional method for this.

**Comment by odow** [comment]
There already is `eval_constraint_jacobian_transpose_product`, so if you're happy with the dense gradient you could do what @frapac suggests.

The sparse gradient is also easy to add though.

**Comment by blegat** [comment]
> > That doesn't work so well then because you get the full jacobian instead of one gradient for each constraint
>
> I proposed that we add an additional method for this.

Looking at https://github.com/jump-dev/MathOptInterface.jl/pull/2200, I was wrong, there is nothing internally that makes gradients less efficient to compute.

**Comment by odow** [comment]
> there is nothing internally that makes gradients less efficient to compute.

This is not quite true, but the difference is subtle. 

We need the NLPBlock structure because we cache a bunch of working vectors, and we re-use nonlinear expressions and parameters. Computing a backward pass also runs over the full model, but we cache that as well, so querying two gradients needs only one backward pass.

The worst-case would be querying the gradient of a single constraint at lots of different points `x`.

**Comment by blegat** [comment]
So querying each gradient separately isn't slower than querying the jacobian right ?
