### ISSUE TITLE
MutableArithmetics/MathOptInterface ambiguity with v1.18.0

### ISSUE THREAD

**Issue by adrienbanse** [jump-dev/MathOptInterface.jl#2222]
New release (v1.18.0) creates an ambiguity between `+` functions of `MutableArithmetics` and `MathOptInterface`.
See https://github.com/dionysos-dev/Dionysos.jl/issues/256 for the whole error message.

cc @blegat

**Comment by blegat** [comment]
This seems to have been introduced in https://github.com/jump-dev/MathOptInterface.jl/pull/2213

**Comment by odow** [comment]
Do you have a reproducible example? How did the `+(::MA.Zero, ::VariableRef)` end up being called?

**Comment by blegat** [comment]
I wrote that:
https://github.com/dionysos-dev/Dionysos.jl/blob/a530b52716f352c6cbd6330b7103005175884641/src/optim/bemporad_morari.jl#L430

**Comment by adrienbanse** [comment]
The problem is with the first `operate!!` line https://github.com/dionysos-dev/Dionysos.jl/blob/a530b52716f352c6cbd6330b7103005175884641/src/optim/bemporad_morari.jl#L463C1-L463C61
