### ISSUE TITLE
Unsatisfiable requirements detected for package MathOptInterface

### ISSUE THREAD

**Issue by kocvara** [jump-dev/MathOptInterface.jl#2238]
Trying to run Documentation.yml on github.com/kocvara/Loraine.jl, ending with an error shown below. Clearly, I'm doing something wrong?

Thanks for any hint, Michal

ERROR: Unsatisfiable requirements detected for package MathOptInterface [b8f27783]:
 MathOptInterface [b8f27783] log:
 ├─possible versions are: [0.5.0-0.5.1, 0.6.0-0.6.4, 0.7.0, 0.8.0-0.8.4, 0.9.0-0.9.22, 0.10.0-0.10.9, 1.0.0-1.0.2, 1.1.0-1.1.2, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0-1.6.1, 1.7.0, 1.8.0-1.8.2, 1.9.0, 1.10.0, 1.11.0-1.11.5, 1.12.0, 1.13.0-1.13.2, 1.14.0-1.14.1, 1.15.0-1.15.1, 1.16.0, 1.17.0-1.17.1, 1.18.0] or uninstalled
 ├─restricted to versions 1 by Loraine [df0521af], leaving only versions [1.0.0-1.0.2, 1.1.0-1.1.2, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0-1.6.1, 1.7.0, 1.8.0-1.8.2, 1.9.0, 1.10.0, 1.11.0-1.11.5, 1.12.0, 1.13.0-1.13.2, 1.14.0-1.14.1, 1.15.0-1.15.1, 1.16.0, 1.17.0-1.17.1, 1.18.0]
 │ └─Loraine [df0521af] log:
 │   ├─possible versions are: 0.1.2 or uninstalled
 │   └─Loraine [df0521af] is fixed to version 0.1.2
 └─restricted by julia compatibility requirements to versions: [0.5.0-0.5.1, 0.6.0-0.6.4, 0.7.0, 0.8.0-0.8.4, 0.9.0-0.9.22, 0.10.0-0.10.9] or uninstalled — no versions left

**Comment by Vaibhavdixit02** [comment]
You have restricted julia version to 1.5 https://github.com/kocvara/Loraine.jl/blob/main/Project.toml#L24 but also set compact for MOI at 1 but MOI >= 1 is compatible only with newer julia versions (1.6+). Change the julia compat to "1".

**Comment by kocvara** [comment]
Thanks. I did, however, got just the same error message...

**Comment by blegat** [comment]
What is your Julia version ? What is the output of `VERSION` of `versioninfo()`

**Comment by kocvara** [comment]
Julia v1.9

**Comment by kocvara** [comment]
I just don't understand why the code as such is fine (passing all the tests) but documentation.yml crashes on MOI(?)

**Comment by blegat** [comment]
Here, it is Julia v1.5:
https://github.com/kocvara/Loraine.jl/blob/main/.github/workflows/documentation.yml#L16
Change this line either to `1.6` or `1`. `1` will default to the latest Julia release so `1.9`

**Comment by kocvara** [comment]
Ahh, that was it! I changed in Project.toml but missed this one. Works fine now. Many thanks!
