### ISSUE TITLE
Update ScaledPSDCone

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#2260]
Here are the PSD solvers that were updated to use `ScaledPositiveSemidefiniteConeTriangle` and should be updated to `Scaled{PositiveSemidefiniteConeTriangle}`

- [x] Clarabel https://github.com/oxfordcontrol/Clarabel.jl/pull/141
- [x] SCS https://github.com/jump-dev/SCS.jl/pull/283
- [x] MosekTools https://github.com/jump-dev/MosekTools.jl/pull/133

Here are those that are still using `PositiveSemidefiniteConeTriangle` but could be updated to use `Scaled{PositiveSemidefiniteConeTriangle}`

- [ ] Hypatia
- [x] COSMO https://github.com/oxfordcontrol/COSMO.jl/pull/181

**Comment by odow** [comment]
Is there anything to do here? Hypatia didn't support `ScaledPositiveSemidefiniteConeTriangle` anyway.
