### ISSUE TITLE
Implement empty! and is_empty for MOI.Nonlinear.Model

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#2302]
Would be useful for https://github.com/JuliaManifolds/Manopt.jl/pull/264

**Comment by odow** [comment]
Just build a new one? `MOI.Nonlinear.Model` does not follow the full MOI API.

**Comment by blegat** [comment]
Indeed, it's a bit confusing it does not

**Comment by odow** [comment]
Not really, it doesn't add variables via `add_variable`, it doesn't manage the objective via `set(m, ::ObjectiveFunction)` because the function type is `Expr`, and so on. It's not a heavy lift to have to create a new one rather than call `empty!`.

**Comment by odow** [comment]
You don't really need this for ManOpt: https://github.com/JuliaManifolds/Manopt.jl/pull/264/files#r1348482364

And I guess for ipopt we could check if `nlp_model === nothing`, but it's not really important.
https://github.com/jump-dev/Ipopt.jl/blob/e01818b6bde26ef779df08be9108694e75613b41/src/MOI_wrapper.jl#L105C5-L105C20
