### ISSUE TITLE
[Utilities] Add support for filtering variables in ModelFilter

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#2308]
Needs to be added here:

https://github.com/jump-dev/MathOptInterface.jl/blob/eb0d3c1a0687eb55adecfa35a7f583654b9d212c/src/Utilities/copy.jl#L512-L584

Once added, we should also add to JuMP's `copy_model`.

cc @sstroemer

**Comment by sstroemer** [comment]
Nice, thanks for the pointer. Since I'm probably the only one needing this right now, I'll come up with a PR in the upcoming weeks!

**Comment by odow** [comment]
So I started to take a look at this. I think it might be easier to just copy the full model and then delete variables from the copy. Filtering the variables on copy is just a recipe for bugs, because we can't filter the variables from individual constraints and attributes.

**Comment by odow** [comment]
Closing as won't-fix. If any future reader objects and has an example where deleting after copy doesn't work for some reason, please comment and we can have another discussion.
