### ISSUE TITLE
Get list of indices with non-default attribute values

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#2317]
@bernalde hit me up at INFORMS with this problem:

 * Given `MOI.VariablePrimalStart` appears in `MOI.ListOfVariableAttributesSet`, how do I tell which variables have a non-default start?

Some possible solutions:

 1. You don't. Iterate over every variable
 2. Add new attributes:
     * `MOI.ListOfVariablesWithAttributeSet{A<:MOI.AbstractVariableAttribute}`
     * `MOI.ListOfConstraintsWithAttributeSet{F,S,A<:MOI.AbstractConstraintAttribute}`

We could potentially implement 2. with the default that falls back to `MOI.get(model, MOI.ListOfVariableIndices())`. This would let solvers opt-in to more efficient implementations. But it might also confuse users if they start using `MOI.ListOfVariablesWithAttributeSet` and find that it is a super-set of indices, rather than the exact set.

**Comment by blegat** [comment]
What do we do the fallback for a custom attribute ? Should we interpret `nothing` as nothing has been set for any attribute ?

**Comment by odow** [comment]
> Our application relies heavily on the use of many types of variable attributes

Can you link to the code?

**Comment by odow** [comment]
> What do we do the fallback for a custom attribute ?

I think the idea would be to keep track of every index that has been modified for every attribute. You don't need to know the value, just that it has been set. But this is a lot of record keeping...especially with all the different layers.

**Comment by blegat** [comment]
`UniversalFallback` already have a sparse representation of these list so it would actually be easy to implement

**Comment by odow** [comment]
Yeah, I think the argument against doing this is that it's quite a heavy lift for all the packages to start implementing.

**Comment by blegat** [comment]
They don't have to do anything, the fallback gives the current behavior
