### ISSUE TITLE
Print a constraint with Name

### ISSUE THREAD

**Issue by WalterMadelim** [jump-dev/MathOptInterface.jl#2335]
While building a model with Gurobi.jl and MOI, variable names is visiable from `print(model)`, but constraint names are not. I think this is inconsistent.
```julia
julia> import MathOptInterface as MOI
julia> import Gurobi
julia> o = Gurobi.Optimizer();
julia> x = MOI.add_variable(o);
julia> ci = MOI.add_constraint(o, 1. * x, MOI.LessThan(0.))
MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}(1)

julia> print(o) ### model_print_1
Feasibility

Subject to:

ScalarAffineFunction{Float64}-in-LessThan{Float64}
 0.0 + 1.0 v[1] <= 0.0

julia> MOI.set(o,MOI.VariableName(),x,"x") ### set Variable Name

julia> print(o) ### model_print_2
Feasibility

Subject to:

ScalarAffineFunction{Float64}-in-LessThan{Float64}
 0.0 + 1.0 x <= 0.0 ### Variable Name updated from "v[1]" to "x", compared with model_print_1

julia> MOI.set(o,MOI.ConstraintName(),ci,"x_le_0") ### set Constraint Name

julia> print(o) ### model_print_3, which is the same as model_print_2
Feasibility

Subject to:

ScalarAffineFunction{Float64}-in-LessThan{Float64}
 0.0 + 1.0 x <= 0.0

julia> 
```
I think an ideal case in model_print_3 should be something like
```julia
julia> print(o)
Feasibility

Subject to:

ScalarAffineFunction{Float64}-in-LessThan{Float64}
x_le_0: 0.0 + 1.0 x <= 0.0
```
Do you think this is a good proposal, because when users model physical problems, they need to label constraints of different types (e.g., ramp_up rates, demand_balance,...)
It will be convenient to check them in the prints.

Or maybe this is a question with MOI, generally?

Thanks!

**Comment by odow** [comment]
Transferred this to MOI.

```julia
julia> import MathOptInterface as MOI

julia> model = MOI.Utilities.Model{Float64}()
MOIU.Model{Float64}

julia> x = MOI.add_variable(model)
MOI.VariableIndex(1)

julia> ci = MOI.add_constraint(model, 1.0 * x, MOI.LessThan(0.0))
MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}(1)

julia> MOI.set(model, MOI.VariableName(), x, "x")

julia> MOI.set(model, MOI.ConstraintName(), ci, "x_le_0")

julia> print(model)
Feasibility

Subject to:

ScalarAffineFunction{Float64}-in-LessThan{Float64}
 0.0 + 1.0 x <= 0.0
```

We do not print constraint names:

https://github.com/jump-dev/MathOptInterface.jl/blob/46f1db183246ba85ede1b9243fff241541654f46/src/Utilities/print.jl#L370-L382

**Comment by odow** [comment]
I don't remember why we don't do this, but is it really important? Printing the MOI model should be a very rare occurrence.

**Comment by WalterMadelim** [comment]
Well, actually I'm using MOI heavily currently, since I'm a professional user. I would like to use MOI's functional APIs, along with a specific Solver.jl (e.g. Gurobi.jl, SCIP.jl, etc.) I prefer to write code in this style and they fulfill my (specialized) needs.

Recently I've finished e.g., 
*  the modeling of 2-stage-SSLP problem, with the latest algorithm from https://doi.org/10.1287/ijoc.2022.1185, in https://github.com/WalterMadelim/p8f.jl/blob/main/src/sslp_SB_cut.jl
*  the modeling of multi-stage-UC problem, which is from https://doi.org/10.1007/s10107-021-01740-0, in https://github.com/WalterMadelim/p8f.jl/blob/main/src/UnitComm6.jl

I think it would be better to add such a function, because the modification of variable name is visible already. Otherwise, what is the function of `MOI.set(model, MOI.ConstraintName(), ci, "ci_name")`, how can I check it?

Thanks,
Sincerely 😊

**Comment by odow** [comment]
> Otherwise, what is the function of 

They're passed to the solver for diagnostics, used when writing file formats, and used by JuMP for printing. I guess there's no harm in also printing them here.
