### ISSUE TITLE
`MOI.get` on attribute where `is_set_by_optimizer = true` and `TerminationStatus = OPTIMIZE_NOT_CALLED`

### ISSUE THREAD

**Issue by pedromxavier** [jump-dev/MathOptInterface.jl#2352]
On the series of querying attributes with our meta-solver/reformulator I encountered a corner case when retrieving attributes after reformulation without an inner optimizer.

Basically, we have an operation mode in [psrenergy/ToQUBO.jl](https://github.com/psrenergy/ToQUBO.jl) where a call to `optimize!` without an optimizer will just reformulate the problem to the QUBO form, e.g.,

```julia
model = Model(ToQUBO.Optimizer)
...
optimize!(model)
```

instead of the usual

```julia
model = Model(
    () -> ToQUBO.Optimizer(QuantumSolver.Optimizer)
)
...
optimize!(model) # Returns termination status from `QuantumSolver`
```

The problem is that the `OPTIMIZE_NOT_CALLED` status prevents attribute retrieval for cases where `is_set_by_optimizer = true`.

I couldn't find any other suitable status for this case besides `OTHER_ERROR` which is kind of misleading since there was no error to begin with.

**Note**: Using `optimize!` is not necessary, we could be using something like `reformulate!` or `compile!` but this makes no big difference in the issue.

**Comment by odow** [comment]
I don't know if I fully understand the issue. Do you have a reproducible example? What attribute do you want to query if the problem hasn't been set?

If you don't call `optimize!`, then by definition you can't query attributes that `is_set_by_optimizer = true`.

If you want `ToQUBO.Optimizer` to reformulate the problem on `optimize!` and make some attributes available, then it should implement `MOI.optimize!` and return an appropriate termination status.  I guess you could use `LOCALLY_SOLVED`?

**Comment by pedromxavier** [comment]
I think the question boils down to choosing the appropriate status. The problem I see with `LOCALLY_SOLVED` is that there will be no solutions available. Is it enough to set `ResultCount = 0` and `NO_SOLUTION` for `PrimalStatus` and `DualStatus`?

PS: An example would look like:

```julia
# Create the model
model = Model(
    # Use ToQUBO in compilation mode
    () -> ToQUBO.Optimizer(nothing)
)

# Add the variables
@variable(model, 0 <= x[1:2] <= 1)
# Add the objective
@objective(model, Min, sum(x .^ 2))

# Add the global constraint
@constraint(model, alpha, sum(x) >= 0.5)

# Compile the QUBO model
optimize!(model)

get_attribute(alpha, ToQUBO.Attributes.ConstraintEncodingPenalty()) # Error!
```

**Comment by odow** [comment]
> Is it enough to set ResultCount = 0 and NO_SOLUTION for PrimalStatus and DualStatus?

Yes, this should work.

**Comment by blegat** [comment]
> I couldn't find any other suitable status for this case besides `OTHER_ERROR` which is kind of misleading since there was no error to begin with.

You could also consider that the error is that there was no solver attached. I think it's more important to have the `RawStatusString` detail clearly what happens so that `solution_summary` is clear and the user that forgot to give an optimizer is not confused.

**Comment by odow** [comment]
Is there anything actionable left to do here? This seems like it can be fixed in ToQUBO, not in MOI.

**Comment by pedromxavier** [comment]
@odow I think this is indeed very specific to our use case, so I don't think it's even something that is missing from the docs. Maybe, for ToQUBO and other reformulators/meta-solvers a `REFORMULATION_COMPLETE` or `REFORMULATION_ONLY` status would be the best fit, ideally speaking.

And yes, the question was answered and this issue looks ready to be closed, thanks!

**Comment by odow** [comment]
I think `LOCALLY_SOLVED` + `NO_RESULT` + an informative description in `RawStatusString` is enough. The solver terminated normally, and it did not find a primal solution.
