### ISSUE TITLE
Order of model attributes during copy

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#2366]
As reported in https://github.com/jump-dev/MathOptInterface.jl/issues/2363#issuecomment-1862620395, the `SlackBridgePrimalDualStart` is ignored if it is copied before the objective is set which depends on the order of the model attributes.

**Comment by odow** [comment]
Yeah... this is a bit messy. Perhaps we should have:

 * UserDefinedFunction
 * ObjectiveSense
 * ObjectiveFunction

all others.

The real fix would be to define a priority and then sort by that.
