### ISSUE TITLE
MOI slow to import and precompile

### ISSUE THREAD

**Issue by theogf** [jump-dev/MathOptInterface.jl#2442]
I noticed that when running

```
@time_imports using Optim
```

Most of the time was taken by MathOptInterface:

```
2243.5 ms  MathOptInterface
22.1 ms  Optim
```

Additionally the precompilation takes a really long time. It surprising for a package that is supposed to be an interface?

This was run on Julia 1.9.3

**Comment by odow** [comment]
Regardless. Closing this as won't fix. You could open an issue at Optim.jl about moving MathOptInterface to a package extension.

**Comment by blegat** [comment]
Yes, it could be moved as a package extension

**Comment by theogf** [comment]
Cool! I'll make a PR to Optim.jl then!
