### ISSUE TITLE
Add function to summarize model "size"?

### ISSUE THREAD

**Issue by ericphanson** [jump-dev/MathOptInterface.jl#2504]
This came up in https://github.com/jump-dev/Convex.jl/pull/643; it would be nice to have some kind of summary of model size (# scalar variables, constraints, coefficients) easily accessible, so Convex.jl users can get a summary of the final formulation. I think being able to print some stats is a convenient way to get a glimpse into this (and something we could potentially surface automatically via printing in Convex.jl, which would led users build intuition for the final model without having to necessarily seek it out). Something like a full summary of all the cones used, their sizes, etc, could be useful too (but possibly too verbose for some use-cases).

**Comment by odow** [comment]
Yeah I quite like a default `show`, like we do for JuMP.
