### ISSUE TITLE
Clarification about the naming of the two constraint jacobian product evaluators

### ISSUE THREAD

**Issue by Vaibhavdixit02** [jump-dev/MathOptInterface.jl#2535]
I wanted to confirm if my understanding of the names of the two constraint jacobian evaluators `eval_constraint_jacobian_product` is `J*v` and `eval_constraint_jacobian_transpose_product` is `v^T*J`?

**Comment by odow** [comment]
I'm drafting a PR to improve these docstrings and add examples.

**Comment by Vaibhavdixit02** [comment]
Ah, I was looking here https://github.com/jump-dev/MathOptInterface.jl/blob/master/src/Nonlinear/evaluator.jl#L210 and didn't see the docstring, sorry should've just checked the documentation! 😅
