### ISSUE TITLE
`MathOptInterface` not defined

### ISSUE THREAD

**Issue by LD-FW** [jump-dev/MathOptInterface.jl#2546]
I am trying to implement the project found at 
https://github.com/TILOS-AI-Institute/HypergraphPartitioning/tree/main/SpecPart
, but I am encountering some issues. 
When I execute the command `julia> include("SpecPart/SpectralRefinement.jl")`, I receive the following error:
ERROR: LoadError: UndefVarError: `MathOptInterface` not defined
Stacktrace:
 [1] include(mod::Module, _path::String)
   @ Base ./Base.jl:495
 [2] include(x::String)
   @ Main.SpectralRefinement ~/Documents/HypergraphPartition/SpecPart/SpectralRefinement.jl:1
 [3] top-level scope
   @ ~/Documents/HypergraphPartition/SpecPart/SpectralRefinement.jl:23
 [4] include(fname::String)
   @ Base.MainInclude ./client.jl:489
 [5] top-level scope
   @ REPL[2]:1
in expression starting at /home/fw23/Documents/HypergraphPartition/SpecPart/PartitionILP.jl:3
in expression starting at /home/fw23/Documents/HypergraphPartition/SpecPart/SpectralRefinement.jl:1

I checked the installed packages using `Pkg.status()`, and I found the package [b8f27783] MathOptInterface v1.31.2 installed.
 Additionally, I tried adding `using MathOptInterface` and `import MathOptInterface` at the beginning of both `PartitionILP.jl` and `SpectralRefinement.jl`, but I still get the same error.
![1](https://github.com/user-attachments/assets/db7ebd4c-bcef-42b3-b454-256d4ec65a6f)

**Comment by odow** [comment]
Closing because this is not an issue in MathOptInterface.

This is a bug in https://github.com/TILOS-AI-Institute/HypergraphPartitioning/pull/11
