### ISSUE TITLE
Numerical Error in Nonlinear Test

### ISSUE THREAD

**Issue by DimitriAlston** [jump-dev/MathOptInterface.jl#2550]
I believe there may be an issue here: 
https://github.com/jump-dev/MathOptInterface.jl/blob/24012962dd89e36b413469a3c85b26491898c749/src/Test/test_nonlinear.jl#L1391-L1400

The interval on each x should be `Interval(2.001, 9.999)` instead of `Interval(-2.001, 9.999)` for `log(x - 2)` to be defined.

Here's an example using Ipopt,
```julia
using JuMP, Ipopt
model = Model(Ipopt.Optimizer);

@variable(model, -2.001 <= x[1:10] <= 9.999);

f = log(x[1] - 2)^2 + log(10 - x[1])^2;
for i = 2:10
    f += log(x[i] - 2)^2 + log(10 - x[i])^2
end
f -= (x[1] * x[2] * x[3] * x[4] * x[5] * x[6] * x[7] * x[8] * x[9] * x[10])^0.2;

@objective(model, Min, f);

JuMP.optimize!(model)
```
which returns `EXIT: Invalid number in NLP function or derivative detected.`
If the variables are defined as `@variable(model, 2.001 <= x[1:10] <= 9.999)` instead, then the solution is found.

**Comment by odow** [comment]
It does look like it should be `+2.001` :smile:
