### ISSUE TITLE
Explain SOC-via-quadratic test

### ISSUE THREAD

**Issue by mlubin** [jump-dev/MathOptInterface.jl#307]
https://github.com/JuliaOpt/MathOptInterface.jl/blob/29b16b10f11ebaf41b3f1c97bfc7ff68ad5b86d6/src/Test/contquadratic.jl#L466-L473

The existence of this test is pretty confusing. It deserves a comment on why solvers would want to test this and if solvers should be expected to support it given that we have a more natural way to express SOC constraints in MOI.

My take is that solvers should only support this if it doesn't require extra processing in the wrapper, e.g., in Gurobi. OTOH, if it doesn't require extra processing and we've already tested QCQPs, what extra coverage is provided by this test?

**Comment by blegat** [comment]
> My take is that solvers should only support this if it doesn't require extra processing in the wrapper, e.g., in Gurobi

I agree, solvers supporting SOC constraints, can be used with quadratic constraints using https://github.com/JuliaOpt/MathOptInterfaceBridges.jl/issues/93 just like it was done by the LPQPtoConic wrapper in MPB so the solver only needs to implement support for the constraint closest to the interface of the solver wrapped.

> OTOH, if it doesn't require extra processing and we've already tested QCQPs, what extra coverage is provided by this test?

If a solver only support quadratic constraints and not SOC constraints (e.g. Gurobi, ...), it is nice to have an additional test that is less trivial than the tests in `qcp`. It could be moved from the `socp` category to the `qcp` category though.

**Comment by joaquimg** [comment]
Gurobi and Xpress do not have a natural SOC interface, so they use the QCP interface for SOCP.
I agree we could add comments and move that test to QCP category.
No extra processing is required by these solvers when the constraint is sent this way.
