### ISSUE TITLE
Bridge request: GeometricMeanCone to PowerCone

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#406]
@ulfworsoe presented [JuMP-dev](http://www.juliaopt.org/meetings/bordeaux2018/) a reformulation of the Geometric Cone using Power Cone.
The transformation [we use currently](https://github.com/JuliaOpt/MathOptInterface.jl/blob/8e53b2e79cd329e541d9c0ff020101450c403c6b/src/Bridges/geomeanbridge.jl) uses the Rotated Second Order Cone.
As discussed at the end of the talk, even if adding a RSOC constraint has a smaller impact on performance than adding a Power cone, the number of constraints grows more rapidly for the reformulation with RSOC so for solver supporting Power Cones, the default bridge should be the one with Power Cones.

**Comment by odow** [comment]
The reformulation is
![image](https://user-images.githubusercontent.com/8177701/173493690-ca696b1b-4959-4086-ad92-1195e993bd03.png)
