### ISSUE TITLE
ScalarFunctionIterator has quadratic complexity

### ISSUE THREAD

**Issue by mohamed82008** [jump-dev/MathOptInterface.jl#418]
The current `ScalarFunctionIterator` has a best case quadratic and worst case cubic (if the constraints are dense) complexity. If we do a Radix sort by the `output_index` then it becomes O(nk) where k is the average number of terms per constraint. For sparse constraints, this is linear complexity. This together with the use of `StructsOfArrays.jl` can enable returning a view from `scalar_terms_at_index` which reduces allocations. The catch here is if the user/solver expects the terms to be in a certain order and sorting will just confuse everyone. I haven't seen this assumption made anywhere so I am asking if you know otherwise.

https://github.com/JuliaOpt/MathOptInterface.jl/blob/247c4baf673eb8b1c29177e7f1652a0a78e1d570/src/Utilities/functions.jl#L103

**Comment by odow** [comment]
We should hold off until we can benchmark the performance. Where is this used in the rest of the code?

**Comment by mohamed82008** [comment]
> Where is this used in the rest of the code?

I am still reading so I am not sure but this seems like the kind of thing I would assume is efficient since it is baked in MOI. Maybe others know where it is used.

**Comment by mohamed82008** [comment]
Shouldn't be hard to benchmark this specific part of the code using random sparse matrices of `ScalarAffineTerms` which are converted to `VAF`s, then iterated over. I will try to do it and see what happens.

**Comment by blegat** [comment]
`getindex` used to be called directly on the `AbstractVectorFunction`.
Now that it `eachscalar` is called first, we could add caching in the `ScalarFunctionIterator` to avoid having to redo `findall` for every `getindex`.
We could for instance have a `Vector{Vector{Int}}` stored in cache storing the list of indices of terms for a specific output index. This can be constructed from a single pass through the terms in `eachscalar`.

**Comment by mohamed82008** [comment]
This is a nice middle way solution that does not involve the hidden sorting of the terms. Sorting will probably use less memory but may be an unexpected and unwelcome side effect.

**Comment by mohamed82008** [comment]
If memory is not of primary concern, we can also cache a sorted version of the vector of terms and a vector of end markers for the rows' terms. This will enable using the StructsOfArrays trick, which will save allocations by returning a view into the sorted vector of terms.

**Comment by blegat** [comment]
The `ScalarAffineFunction` terms need to be a `Vector`, not any `AbstractVector` so it cannot be a view, can it ?

**Comment by mohamed82008** [comment]
True, but that's something that will also have to change :) Parameterizing by the vector type is the first step towards native GPU solver support. It's also good for cases like this to avoid allocations using views.

**Comment by mohamed82008** [comment]
That's a discussion for another thread though.

**Comment by blegat** [comment]
This will completely copy all the terms of the function in the sorting so if the user only wants to obtain the scalar function at one index, it might be overkill to create the list of sorted terms.
Putting the indices of the terms of each output index in different buckets is the first step of the radix sort so it makes sense to cache that and have fast creation of scalar function when needed.
If we parametrize by the vector type the view idea makes sense. IIRC, it has already been discussed and we decided against the idea to keep a simpler interface. We might reconsider but it might take time to change this. If you want this issue to be fixed in a reasonable amount of time, it is probably best not to rely on this :)

**Comment by mohamed82008** [comment]
Coming up in a PR.

**Comment by dourouc05** [comment]
Now that #1257, maybe the comment in https://github.com/jump-dev/MathOptInterface.jl/blob/d816122fcbc5beeac8d7782fb02feab14fca4840/src/Utilities/functions.jl#L2864-L2865 should be removed?

**Comment by blegat** [comment]
Yes, the speed difference should be smaller

**Comment by dourouc05** [comment]
I thought so, so it's already part of #1553.
