### ISSUE TITLE
Setting names is very slow, does a lot of work, some of it redundant

### ISSUE THREAD

**Issue by IainNZ** [jump-dev/MathOptInterface.jl#452]
In particular, the code here:
https://github.com/JuliaOpt/JuMP.jl/issues/1402#issuecomment-410538362
stress tests the `setname` logic and shows it allocates quite a bit, and takes a lot of time.

**Comment by mlubin** [comment]
https://github.com/JuliaOpt/MathOptInterface.jl/blob/c164eabcff67e6d96341e69eb053e6fc01b5e3a3/src/Utilities/model.jl#L188-L191

The code here does a hash and lookup on the name 3 times if I'm counting correctly between the `canget`s and the `get`.

Also is this string always constructed or only if the error case hits?
https://github.com/JuliaOpt/MathOptInterface.jl/blob/c164eabcff67e6d96341e69eb053e6fc01b5e3a3/src/Utilities/model.jl#L162

**Comment by IainNZ** [comment]
More tests - commenting out the checks actually doesn't affect run time much - rather, the two lines of storing stuff does.

**Comment by mlubin** [comment]
We're also missing `hash` implementations for the index types. That made a big difference in my previous benchmarks.

**Comment by IainNZ** [comment]
```julia
struct VariableIndex
    value::Int64
end
Base.hash(index::VariableIndex, h::UInt) = hash(index.value, h)

function run_moi_str_test()
    model = VariableIndex[]
    varnames = Dict{VariableIndex, String}()
    namesvar = Dict{String, VariableIndex}()
    for i in 1:10^6
        vi = VariableIndex(i)
        push!(model, vi)
        name = string("vars", "[", i, "]")
        varnames[vi] = name
        namesvar[name] = vi
    end
end
```

* As is, this is about 1.95 seconds, 8e6 allocations.
  * Julia 0.7 is a bit faster, ~1.9 seconds.
* Replacing `name = string(i)` gives 0.7 seconds, 2e6 allocations.
  * Julia 0.7 is a bit faster, ~0.65 seconds.
* Without the custom hash there are more allocations, but not in a way that seems to affect runtime.

**Comment by tkoolen** [comment]
Does `varnames` have to be a `Dict`? Why not use a `Vector{String}` indexed by `VariableIndex`? Typically, the `VariableIndex`es for a model will be contiguous, right? Or if you want to keep the `AbstractDict` semantics, you could use something like https://github.com/JuliaRobotics/RigidBodyDynamics.jl/blob/9c96a4420f46e74ce3fa009a7453455bc68ab8b6/src/custom_collections.jl#L105-L131.

**Comment by blegat** [comment]
When you delete variables, there will be holes, how do you handle that ?

**Comment by tkoolen** [comment]
I suppose either a `Vector{Union{String, Nothing}}` or a `CardinalDict` from https://github.com/JeffreySarnoff/CardinalDicts.jl?

**Comment by blegat** [comment]
We will benchmark
```julia
name = vec[index]
if name === nothing
    throw(MOI.InvalidIndex(index))
end
return name::String
```
against
```julia
if haskey(cardinal_dict, index)
     throw(MOI.InvalidIndex(index))
end
return cardinal_dict[index]
```

**Comment by odow** [comment]
Closing because all the bottleneck is setting the name in the dict here:
https://github.com/jump-dev/MathOptInterface.jl/blob/f49fde00e5404d200f7c5b59d7d8cbbedabd12fa/src/Utilities/model.jl#L353-L355
```Julia
function run_test()
    model = JuMP.Model()
    JuMP.@variable(model, vars[1:10^6])
    return model
end
run_test()
Profile.init(n=Int(1e8), delay=0.00000001)
@pprof run_test()
```
![image](https://user-images.githubusercontent.com/8177701/109601072-206eda00-7b83-11eb-8844-237ff712d1c8.png)

But even adding a million variables only takes 0.5 seconds.
```julia
julia> @time run_test();
  0.583714 seconds (6.00 M allocations: 344.590 MiB)
```

There are bigger fish to fry.
