### ISSUE TITLE
lazy_operate

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#526]
If the vector type of function is made abstract as suggested in https://github.com/JuliaOpt/MathOptInterface.jl/issues/525, that would allow to implement `lazy_operate` which would be useful for bridges as explained in https://github.com/JuliaOpt/MathOptInterface.jl/issues/523

**Comment by odow** [comment]
Closing as vague, and because we haven't made any progress since 2018. We can revisit it in future if needed.
