### ISSUE TITLE
Set request: ScaledPSDCone

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#531]
The scaled PSD cone was removed in https://github.com/JuliaOpt/MathOptInterface.jl/issues/176 arguing that it is not useful when modeling.
However, some solvers such as SCS and Mosek uses it internally and need to transform the unscaled PSD coefficients to the PSD coefficients and also transforming constraintprimal and constraintdual values.
If we add the scaled PSD cone back, these transformations could be factored out of the solver wrappers into a bridge in MOI.
This might seem inefficient to have a bridge for such simple transformation but in fact if implemented as a light bridge (see https://github.com/JuliaOpt/MathOptInterface.jl/issues/523), it shouldn't have more overhead that the transformation currently carried out in the solver wrappers. At least there would be only one place to check for performance.
What do you think ? Should we bring it back ?

* Bring it back ! :+1: 
* Do not bring it back ! :-1:

**Comment by chriscoey** [comment]
Yes please!

**Comment by chriscoey** [comment]
Looks like we can move ahead with this?

**Comment by mlubin** [comment]
Do we *really* need three versions of the PSD cone? It's a lot of complexity to manage within MOI.

Light bridges could shift the balance, but they don't exist yet.

**Comment by chriscoey** [comment]
What is the timeline for the lighter bridges?

**Comment by mlubin** [comment]
After JuMP 0.19

**Comment by chriscoey** [comment]
Ok. This year?

**Comment by mlubin** [comment]
I don't know. I wouldn't recommend blocking your work on it.

**Comment by chriscoey** [comment]
The level of complexity that will need to be introduced on the solver side is unacceptable. I will wait. @blegat I'm prepared to help.

**Comment by odow** [comment]
I added the scaled PSD cone to SCS here: https://github.com/jump-dev/SCS.jl/pull/219, along with a bridge from `PositiveSemidefiniteConeTriangle`. 

A bigger issue than the scaling, which is easy to deal with, is the permutation of the cone. For now I think we're okay with non-standard bridges in the packages. We can revisit if lots of solvers end up using the same bridge and set.

**Comment by odow** [comment]
I'm going to close this issue. We don't need more complications at the MOI level.

We now have a good way for solvers to define their own bridges and expose them via the `ListOfNonstandardBridges` attribute.

There are also some differences with how the matrices are permuted (lower triangular or upper triangular), so the best course of action is to look at the SCS set and bridge and make the appropriate changes:

https://github.com/jump-dev/SCS.jl/blob/master/src/MOI_wrapper/scaled_psd_cone_bridge.jl
