### ISSUE TITLE
test that ConstraintPrimal returns exact value of function at result point (not set constant) 

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/MathOptInterface.jl#564]
see http://www.juliaopt.org/MathOptInterface.jl/dev/apireference/#MathOptInterface.ConstraintPrimal

this would help detect issues like https://github.com/JuliaOpt/ECOS.jl/issues/81

the test should check (exact) equality, not approximate equality

**Comment by chriscoey** [comment]
from the definition:
> Given a constraint function-in-set, the ConstraintPrimal is the value of the function evaluated at the primal solution of the variables

to me that suggests returning `b - Ax` not `s`

**Comment by mlubin** [comment]
Then we need to tweak the definition. The intention was what I just wrote.

**Comment by chriscoey** [comment]
do you have any example use cases? why did you decide `s` instead of `b - Ax` for solvers that require slacks?

**Comment by chriscoey** [comment]
and is there a plan to have a bridge that converts non-slack constraints to equalities and slack constraints?

**Comment by mlubin** [comment]
SCS's solution is described by `(x*, s*, y*)` where `x` is the primal, `s` is the slacks, and `y` is the duals (https://github.com/cvxgrp/scs). If we map `ConstraintPrimal` and `ConstraintPrimalStart` to `s` then we can round-trip between an optimal SCS solution and an optimal starting point with no loss of information.

**Comment by mlubin** [comment]
> and is there a plan to have a bridge that converts non-slack constraints to equalities and slack constraints?

Probably, not sure

**Comment by blegat** [comment]
Yes it is planned https://github.com/JuliaOpt/MathOptInterface.jl/issues/528

**Comment by odow** [comment]
I'm not entirely sure how we would test this. Perhaps we just need to update the documentation to mention the slacks?
