### ISSUE TITLE
TestConfig should have option `delete`

### ISSUE THREAD

**Issue by rschwarz** [jump-dev/MathOptInterface.jl#607]
Not all implementations of `Optimizer` support deletion of variables or constraints. However, `MOI.delete` is used often in the tests, e.g. in [linear1test](https://github.com/JuliaOpt/MathOptInterface.jl/blob/d8fdaec968a740f918e7031948ed564373d71bcb/src/Test/contlinear.jl#L209).

Note that there is already the option `TestConfig.modify_lhs` but deletion is not guarded in a similar fashion.

**Comment by joaquimg** [comment]
1, 5, 7 and 14 are the linear ones that use `MOI.delete`, you can disable this ones. If you feel some feature of these tests are missing in the other ones you can propose a new one (always appreciated), we are encouraging people to create simpler and more atomic tests.

**Comment by leethargo** [comment]
Yes, I also excluded 11.
The idea of the test config option came up on Gitter, since from my newcomer's point of view, it looked like the first test was the most fundamental (`# Basic solver, query, resolve`).

**Comment by odow** [comment]
Closed by #1408
