### ISSUE TITLE
improve parser for model strings

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/MathOptInterface.jl#631]
see comments on JuMP-dev gitter. it would be nice if a scalar affine function such as `1.2x - y + 1` would parse in a model string (or at least throw more helpful error messages). currently it has to be written as `1.2x + -1y + 1` to parse.

**Comment by odow** [comment]
Leaving a breadcrumb for future readers. Here's where to start:
https://github.com/jump-dev/MathOptInterface.jl/blob/f08c78cc776e36e92270d42912128543d131c025/src/Utilities/parser.jl#L109-L110
