### ISSUE TITLE
Naming consistency

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#641]
I came across an annoying inconsistency developing [MathOptFormat](https://github.com/odow/MathOptFormat.jl). Some structs use `variable::VariableIndex`:
https://github.com/JuliaOpt/MathOptInterface.jl/blob/97c92db2abb05ac8a53cedab0c4a68cc72d2fcf7/src/functions.jl#L40-L42
and other structs use `variable_index::VariableIndex`
https://github.com/JuliaOpt/MathOptInterface.jl/blob/97c92db2abb05ac8a53cedab0c4a68cc72d2fcf7/src/functions.jl#L64-L67

Thoughts on standardizing to `variable`? Because I can see people saying "Why?"

As a con, this is a horribly breaking change...

**Comment by mlubin** [comment]
Standardizing on `variable` seems reasonable. Post 0.19 though.
