### ISSUE TITLE
Document that nothing can be a value provided to set!

### ISSUE THREAD

**Issue by frapac** [jump-dev/MathOptInterface.jl#649]
Hi, I was testing the package [MINLPTests.jl](https://github.com/lanl-ansi/MINLPTests.jl ) with KNITRO, and when running this code: 
```julia
optimizer = with_optimizer(KNITRO.Optimizer)
m = Model(optimizer)

@variable(m, x, start=0.1)
@variable(m, y)

@objective(m, Min, -x-y)
@NLconstraint(m, exp(x-2.0) - 0.5 <= y)
@NLconstraint(m, log(x) + 0.5 >= y)

optimize!(m)
````
I get the following error: 
`ERROR: MathOptInterface.SetAttributeNotAllowed{MathOptInterface.VariablePrimalStart}`. 

I get the same error with Ipopt. After some investigation, it appears that the error does not arise 
in `DirectMode`. In fact, it happens when we set the `VariablePrimalStart` for all variables all in once here:
https://github.com/JuliaOpt/MathOptInterface.jl/blob/master/src/attributes.jl#L286

In this example, as the primal start of `y` is not specified, the type of the array `vector_of_values` in MOI is 
`Union{Nothing, Float64}` 

However, both Ipopt and KNITRO support only `Real` in the setter of `VariablePrimalStart` : 
```julia
function MOI.set(model::Optimizer, ::MOI.VariablePrimalStart, vi::MOI.VariableIndex, value::Real)
...
end
```

The question is: 

- shall we modify the setter in KNITRO and Ipopt to discard by hand primal start of type `Nothing`?
- or shall we filter directly `Nothing` inside MOI?

**Comment by frapac** [comment]
Thanks for the response and the PR! I will mirror the behavior of Ipopt to update KNITRO. If you want help to update MOI documentation, tell me.

**Comment by mlubin** [comment]
Leaving this open so that we don't forget to fix the documentation.

**Comment by joaquimg** [comment]
We want that explicit in the docstring for `set!`?
Because #1136 already added that do `VariablePrimalStart`'s docstring.

**Comment by odow** [comment]
I think it is sufficient to clarify for each attribute where it applies. This won't always be the case, so it isn't appropriate for `set`.
