### ISSUE TITLE
Documentation or tutorial on transitioning from MathProgBase

### ISSUE THREAD

**Issue by ndinsmore** [jump-dev/MathOptInterface.jl#654]
I am working on transitioning a fairly simple Linear Programming problem (```linprog(c, A, sense, b, l, u, solver)``` ) from MathProgBase to MathOptInterface.   I am finding it hard to find a good one to one example that could help with that.   
It would be great that if for a few of most common use case there was a tutorial that would show how people well versed in MathOptInterface would do it.

**Comment by ndinsmore** [comment]
I recently updated the mincost_flow function in LightGraphsFlow: https://github.com/JuliaGraphs/LightGraphsFlows.jl/pull/23 which was already using MathProgBase.   Compaired to the simplicty there JuMP seems fairly heavy.

**Comment by mlubin** [comment]
@ndinsmore MathProgBase won't be disappearing that quickly, so feel free to keep using it until we have an MOI replacement for `linprog`.

I'm biased, but I don't think the JuMP version is that heavy either:
```julia
model = Model(with_optimizer(Clp.Optimizer()))
@variable(model, l[i] <= x[i=1:num_var] <= u[i])
@objective(model, Min, c .* x)
@constraint(model, A * x .== b) # We don't support a 'sense' vector. You have to split the matrix into parts or add constraints individually.
optimize!(model)
result = value.(x)
```

**Comment by ndinsmore** [comment]
@mlubin that sure is simple and as always I am trying to solve a problem, that is more complex than even the mincost_flow.    
From a resource point of view, how does JuMP compare to MathProgBase or MOI?

**Comment by mlubin** [comment]
> From a resource point of view, how does JuMP compare to MathProgBase or MOI?

It's always a good idea to benchmark, but JuMP's overhead is intended to be minimal compared with the time to solve the problem. If that's not the case we consider it a bug.

**Comment by odow** [comment]
Use JuMP directly:

```julia
using JuMP, Ipopt

N = length(lb)
@assert N == length(ub) == length(c) == size(Q, 1) == size(Q, 2) == size(Aeq, 2)

model = Model(with_optimizer(Ipopt.Optimizer, print_level = 0))
@variable(model, lb <= x[1:N] <= ub)
@objective(model, Min, c' * x + 0.5 * x' * Q * x)
@constraint(model, Aeq * x .== beq)
optimize!(model)
```

**Comment by PaulSoderlind** [comment]
Thanks, 

this works once I replace the `@variable(model, lb <= x[1:N] <= ub)` statement with 
`@variable(model, lb[i] <= x[i=1:N] <= ub[i])` 

I must say that JuMP appears to be a bit verbose, does a fine job. I'll make an effort to convert my code to it.

**Comment by PaulSoderlind** [comment]
`@objective(model, Min, c' * x + 0.5 * x' * Q * x)`
does not work in the new JuMP (0.21.1). 

My workaround is 
```
ex1 = @expression(model,c'*x)
ex2 = @expression(model,x'*Q*x)
@objective(model, Min, ex1 + 0.5*ex2)
```

Is there an easier way?

**Comment by blegat** [comment]
@PaulSoderlind Should be fixed by https://github.com/JuliaOpt/MutableArithmetics.jl/pull/40
