### ISSUE TITLE
No definition of interface requirements

### ISSUE THREAD

**Issue by ndinsmore** [jump-dev/MathOptInterface.jl#662]
There is no documentation in the code or the docs about what the required methods for MOI are.  Something a simple as what is in [Julia Interfaces](https://docs.julialang.org/en/latest/manual/interfaces/) would go a long way towards reducing the learning curve and adding consistency across the ecosystem.

**Comment by odow** [comment]
Yes, this is missing. To date, the heuristic is "implement all methods required to pass all tests in `MathOptInterface.Tests` for the class of problems you want to support."

**Comment by odow** [comment]
Closed by #1300
