### ISSUE TITLE
Bridge debugging

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#680]
We should have a way for the LazyBridgeOptimizer to
- [x] Describe why a constraint is not supported: the bridges that could be used and why they cannot be used to figure out what is the missing piece. https://github.com/JuliaOpt/MathOptInterface.jl/pull/861
- [ ] Describe how a constraint is bridged: what are the possibilities, what is chosen and why Bellman-Ford chose this one
- [ ] Show all the bridges that are currently used.

**Comment by odow** [comment]
Leaving a bread-crumb to where Part II was attempted: https://github.com/jump-dev/MathOptInterface.jl/pull/1055
