### ISSUE TITLE
ZeroOneBridge

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#704]
A bridge between ZeroOne constraint and an Integer constraint + an Interval constraint.
This transformation is currently [hardcoded in the Mosek wrapper](https://github.com/JuliaOpt/MosekTools.jl/blob/d274a8381b6548f5ef25ad249e28884a6a557fed/src/constraint.jl#L191-L192).

**Comment by rtwalker** [comment]
If this is still up for grabs/useful, I'd be interested to try!

**Comment by odow** [comment]
It sure is. Here are some bridges to take inspiration from: https://github.com/JuliaOpt/MathOptInterface.jl/tree/master/src/Bridges/Variable
Reach out in the [Gitter channel](https://gitter.im/JuliaOpt/JuMP-dev) if you need help.

**Comment by blegat** [comment]
It can be implemented both as a constraint bridge and a variable bridge. As the variable is not transformed, the constraint bridge will bridge SingleVariable constraint to SingleVariable constraint so a constraint bridge will work. As it's more lightweight since it does not activate subtitution of all things going in and out of the bridge optimizer, I think for these cases it's better to use constraint bridges.
