### ISSUE TITLE
Base.copy sets is not checked for isbits type

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/MathOptInterface.jl#721]
This is very much some nitpicking but raised in #709 

```julia
julia> const lessthan = MOI.LessThan(BigFloat(4.0))
MathOptInterface.LessThan{BigFloat}(4.0)

julia> const lessthan_copy = copy(lessthan)
MathOptInterface.LessThan{BigFloat}(4.0)

julia> lessthan_copy.upper.exp = 4
4

julia> lessthan
MathOptInterface.LessThan{BigFloat}(8.0)
```

`lessthan` has been mutated by a mutation of its copy. I would however argue this "bug" is not significant since:
1. Numbers are supposed to be immutable
2. The fact that `BigXYZ` isn't is an implementation necessity and shouldn't be used

**Comment by Peiffap** [comment]
I might be completely misunderstanding what you're saying here, but I can think of some instances where mutability of `BigXYZ` would in fact be quite useful from a performance point of view.

**Comment by matbesancon** [comment]
@Peiffap yes all I am saying is that numbers are semantically immutable. Using the mutability locally for performance hacks is fine, but shouldn't be used for general usage

**Comment by blegat** [comment]
Copying a `BigInt` does nothing:
```julia
julia> a = big(1)
1

julia> b = copy(a)
1

julia> a === b
true
```
and given that `copy(::Vector)` does not copy it's elements as it's a shallow copy, it seems we should not copy the constant of the set for an immutable `struct`. For functions we copy the constant as the struct is mutable.
I started implementing it in https://github.com/JuliaOpt/MathOptInterface.jl/tree/bl/mutable_set_field but as a second thought I think we should not copy the constant as explained above.

**Comment by odow** [comment]
Is there a case where this is a problem in practice? It obviously hasn't been to date, so I'm tempted to close.

**Comment by matbesancon** [comment]
this hasn't been much of an issue because we don't have many solvers supporting generic number types. I would be ok with closing this, but Hypatia and Tulip might make the issue more real in the future

**Comment by odow** [comment]
Closing until this is an issue in practice.
