### ISSUE TITLE
Add tests for REDUCTION_CERTIFICATE

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/MathOptInterface.jl#749]
Should we add optional conic tests with problems known to be primal or dual ill-posed?

**Comment by odow** [comment]
Do we have any examples of open-source solvers returning REDUCTION_CERTIFICATE? This seems hard to test.

**Comment by chriscoey** [comment]
Currently no. When Hypatia does this in future, we can add some tests then.

**Comment by odow** [comment]
I'm going to close this issue. 

It seems hard to test generically across solvers, and we don't have any solvers other than Mosek which support it.

If we have multiple solvers writing tests for reduction certificates in the future, we can think about adding tests to MOI.
