### ISSUE TITLE
Run basic_constraint_tests for all bridges

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#750]
Now that bridges need to implement `MOI.get` for `MOI.ConstraintFunction` and `MOI.ConstraintSet`, it is good practice to run `basic_constraint_tests` with the constraints that can be bridged.

- [x] flip_sign.jl https://github.com/JuliaOpt/MathOptInterface.jl/pull/755
- [x] geomean.jl https://github.com/JuliaOpt/MathOptInterface.jl/pull/888
- [x] interval.jl
- [x] quadtosoc.jl
- [x] scalarize.jl
- [x] slack.jl
- [x] square.jl https://github.com/JuliaOpt/MathOptInterface.jl/pull/899
- [x] det.jl
- [x] functionize.jl
- [ ] indicator.jl
- [x] rsoc.jl
- [x] soc_to_psd.jl
- [x] vectorize.jl

**Comment by odow** [comment]
Closing in favor of https://github.com/jump-dev/MathOptInterface.jl/issues/820
