### ISSUE TITLE
Move supports_default_copy_to to MOI?

### ISSUE THREAD

**Issue by mlubin** [jump-dev/MathOptInterface.jl#757]
`supports_default_copy_to` is obligatory to implement according to http://www.juliaopt.org/MathOptInterface.jl/dev/apimanual/#Testing-guideline-1 and http://www.juliaopt.org/MathOptInterface.jl/dev/apimanual/#Implementing-copy-1. Should we move it from MOIU to MOI? MOIU should be for helper functions, not for core methods of the API that solvers need to implement.

**Comment by blegat** [comment]
`default_copy_to` is in MOI so it would reference something in MOIU from MOI but apart from that I don't see any reason not to move it to MOI

**Comment by mlubin** [comment]
We can move `default_copy_to` to MOI if it's part of the definition of the solver interface.
