### ISSUE TITLE
Test getting `VariablePrimalStart`

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#794]
See: https://discourse.julialang.org/t/warning-invalid-warm-start-basis-discarded/26403/2
See: https://github.com/JuliaOpt/Gurobi.jl/issues/225

We should add a test like the following to MOIT.
```Julia
model = Gurobi.Optimizer()
x = MOI.add_variables(model, 3)
MOI.set(
    model, 
    MOI.ObjectiveFunction{MOI.ScalarAffineFunction{Float64}}(), 
    MOI.ScalarAffineFunction(
        MOI.ScalarAffineTerm.(1.0, x),
        0.0
    )
)
MOI.add_constraint(model, MOI.SingleVariable(x[2]), MOI.GreaterThan(1.0))
MOI.set(model, MOI.VariablePrimalStart(), x[1], 1.0)
MOI.set(model, MOI.VariablePrimalStart(), x[2], 0.0)
MOI.set(model, MOI.VariablePrimalStart(), x[3], 2.0)
@test MOI.get.(model, MOI.VariablePrimalStart(), x) == [1.0, 0.0, 2.0]

MOI.set(model, MOI.VariablePrimalStart(), x[2], nothing)
@test MOI.get.(model, MOI.VariablePrimalStart(), x) == [1.0, nothing, 2.0]
```

**Comment by QunLin0** [comment]
I got the following message with the above code (noting that I use @show, instead of @test):

Warning, invalid warm-start basis discarded

ArgumentError: ModelLike of type Gurobi.Optimizer does not support accessing the attribute MathOptInterface.VariablePrimalStart()

**Comment by odow** [comment]
@QunLin0, correct. The reason to add these tests is so that the solvers will all support them. At present, we aren't testing setting warm-starts properly, which is why some solvers haven't implemented them correctly.

**Comment by odow** [comment]
Closed by https://github.com/jump-dev/MathOptInterface.jl/pull/1136
