### ISSUE TITLE
Use Bridges.runtests in bridges tests

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#820]
See https://github.com/JuliaOpt/MathOptInterface.jl/pull/819#discussion_r311582930

Variables:
- [x] flip_sign_bridge.jl https://github.com/jump-dev/MathOptInterface.jl/pull/1896
- [x] free_bridge.jl
- [x] rsoc_to_soc.jl
- [x] rsoc_to_psd.jl
- [x] soc_to_rsoc.jl
- [x] vectorize.jl
- [x] zeros_bridge.jl

Constraint
 - [x] det.jl
 - [x] flip_sign.jl
 - [x] functionize.jl
 - [x] geomean.jl
 - [x] geomean_to_relentr.jl
 - [x] indicator_activate_on_zero.jl https://github.com/jump-dev/MathOptInterface.jl/pull/1897
 - [x] indicator_sos.jl https://github.com/jump-dev/MathOptInterface.jl/pull/1895
 - [x] interval.jl https://github.com/jump-dev/MathOptInterface.jl/pull/1895
 - [x] ltgt_to_interval.jl https://github.com/jump-dev/MathOptInterface.jl/pull/1895
 - [x] norm_infinity.jl https://github.com/jump-dev/MathOptInterface.jl/pull/1895
 - [x] norm_one.jl https://github.com/jump-dev/MathOptInterface.jl/pull/1895
 - [x] norm_spec_nuc_to_psd.jl
 - [x] quad_to_soc.jl
 - [x] relentr_to_exp.jl
 - [x] rsoc_soc.jl
 - [x] scalarize.jl https://github.com/jump-dev/MathOptInterface.jl/pull/1895
 - [x] semi_to_binary.jl
 - [x] slack.jl
 - [x] soc_rsoc.jl
 - [x] soc_to_nonconvex_quad.jl
 - [x] soc_to_psd.jl
 - [x] square.jl
 - [x] vectorize.jl
 - [x] zero_one.jl 

Objective
 - [x] functionize.jl
 - [x] slack.jl

**Comment by odow** [comment]
This is greatly improved by https://github.com/jump-dev/MathOptInterface.jl/blob/8d4d9988498d377d379e9244513c2ba418d49419/test/Bridges/Constraint/soc_to_nonconvex_quad.jl#L140-L166. 

But we still need a solution for variable bridges.

**Comment by odow** [comment]
Closing this as done. I've gone through every bridge, tidied them up, added docstrings, and added more tests. They're in a much better state now!
