### ISSUE TITLE
Names for variable bounds

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#832]
@mlubin suggested that https://github.com/JuliaOpt/GLPK.jl/pull/101#discussion_r295583456

> I'm proposing to make setting ConstraintName on SingleVariable constraint into an error. This wouldn't change lookups otherwise.
>
> To look up the bound on a variable, you first look up the variable. The index of the variable gives you the index of the bound constraint.

Is this something for MOI 0.10?

**Comment by blegat** [comment]
Yes, there is a similar issue with Mosek:
https://github.com/JuliaOpt/MosekTools.jl/blob/2474e1798af4fb2f342c2228a34e2c0430aafe17/src/MosekTools.jl#L82-L84

**Comment by mlubin** [comment]
Yes, I'm still in support of this.

**Comment by odow** [comment]
Are we still in support of this change? It would simplify wrappers, but most wrappers are already written.

**Comment by mlubin** [comment]
I'd say so. Names on variable bounds don't make much sense from the POV of any solver.

**Comment by blegat** [comment]
Yes, I'd support changing this. We should define an error for this and check that the solvers now thro that error, e.g., in `basic_constraint_test`
