### ISSUE TITLE
Add constraint bridge for SOS1 and SOS2

### ISSUE THREAD

**Issue by ohmsweetohm1** [jump-dev/MathOptInterface.jl#845]
Since some solvers do not support SOS1 and SOS2 constraints it would be nice have an automatic reformulation.

Edit(odow): in https://github.com/JuliaOpt/Mosek.jl/issues/182 @ohmsweetohm1 provided a helpful [link to the Mosek cookbook](https://docs.mosek.com/modeling-cookbook/mio.html#continuous-piecewise-linear-functions).

**Comment by blegat** [comment]
In the cookbook, they say that a vector of binary variables in SOS1 can be bridged into `sum(x) <= 1`. However, this will not work for a vector of arbitrary variables. There is currently no way to specify that a bridge only works for binary variables.

**Comment by mlubin** [comment]
Agreed. SOS1 and SOS2 constraints are in general not represenable by mixed-integer linear programming. I don't see how we can make a bridge.

**Comment by odow** [comment]
Closing as won't fix.
