### ISSUE TITLE
Matrix bounds

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#942]
While most SDP only allow to create PSD matrices of variables, some solvers allow to to create matrices bounded (in the semidefiniteness sense) by other matrices.
For instance, [PENNON allows to create a matrix `X` of variables in](http://www.penopt.com/doc/pennon0_9.pdf) (cc @mstingl-fau @kocvara):
```
lambda_lower * I <= X <= lambda_upper * I
```
and [SDPNAL allows to create  a matrix `X` of variables in](https://arxiv.org/pdf/1710.10604.pdf)
```
L <= X <= U
```
We could create a set `EigenvalueInterval(lambda_lower, lambda_upper)`, `EigenvalueGreaterThan(lambda_lower)`, `EigenvalueLessThan(lambda_lower)`, `SemidefiniteInteval(L, U)`, `SemidefiniteGreaterThan(L)`, `SemidefiniteLessThan(U)`.
Of course the `...GreaterThan` and `...LessThan` does not have much interest with `VectorAffineFunction` but it can communicate critical problem structure with `VectorOfVariables`.
Of course, the user would be able to use these sets with solvers not supporting it and  `EigenvalueInterval` would be transformed into `SemidefiniteInterval` for SDPNAL:
* `Constraint.SplitIntervalBridge` bridges
  * `EigenvalueInterval` into `EigenvalueGreaterThan` and `EigenvalueLessThan` and
  * `SemidefiniteInterval` into `SemidefiniteGreaterThan` and `SemidefiniteLessThan`.
* A new bridge to transform `Eigenvalue...` to `Semidefinite...`.
* `FlipSignBridge` to transform `...LessThan` to `...GreaterThan`
* A new bridge to transform `SemidefiniteGreaterThan` to `PositiveSemidefiniteConeTriangle`.

In JuMP, the user should be able to do
```julia
@variable(model, Q[1:5, 1:5] in EigenvalueInterval(lambda_lower, lambda_upper))
```

**Comment by odow** [comment]
Why not have `MatrixInterval`, `MatrixLessThan`, and `MatrixGreaterThan`?

**Comment by matbesancon** [comment]
> Why not have MatrixInterval, MatrixLessThan, and MatrixGreaterThan?

Doesn't it sound ambiguous with an element-wise LessThan, GreaterThan?

**Comment by blegat** [comment]
Reading SDPNAL documentation again, it seems `L <= X <= U` was in fact element-wise bounds to it's just `SingleVariable`-in-`Interval` constraints on PSD variables.

**Comment by odow** [comment]
@blegat what is the status of this? Are there any solvers that support these?

**Comment by blegat** [comment]
Just PENNON at the moment as far as I can tell

**Comment by odow** [comment]
Can this be closed? It doesn't seem like a priority for MOI.
