### ISSUE TITLE
Rename field of Complements

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#949]
The field of the Complements set should be renamed as it does not satisfy the convention that it is equal to `MOI.dimension`.
See https://github.com/JuliaOpt/MathOptInterface.jl/issues/947

**Comment by matbesancon** [comment]
is there a possible name for the replacement? `output_dimension` / `half_dimension`?

**Comment by odow** [comment]
I guess another options to define
```Julia
struct Complements <: AbstractVectorSet
    dimension::Int
    Complements(d::Int) = new(2 * d)
end
```

**Comment by matbesancon** [comment]
Can't that be tricks for users (thinking that the argument passed as a dimension is the same as accessed as `c.dimension`)

**Comment by odow** [comment]
Currently people write
```Julia
@constraint(model, [x, y] in Complements(1))
```
so I don't mind what happens so long as that doesn't change.

To be honest, I'm not really sure that this change is critical. Sure it's a convention, but `Complements` is a weird case that doesn't have to follow convention. I would be in favor of closing this issue with no change.

(If anything, we should rename the `dimension(::AbstractSet)` function to be `output_dimension`, but that boat has sailed.)

**Comment by odow** [comment]
Closing because I don't think this needs to change. The usage is documented, and complements is a weird set. Users shouldn't be accessing `.dimension` anyway, they should access `MOI.dimension(set)`.

**Comment by odow** [comment]
This inconsistency annoyed me here: https://github.com/jump-dev/MathOptInterface.jl/pull/1332. I changed my mind.
