### ISSUE TITLE
Add unit test for UnsupportedAttribute

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#957]
See https://github.com/oxfordcontrol/OSQP.jl/issues/71 and https://github.com/oxfordcontrol/COSMO.jl/issues/97

**Comment by odow** [comment]
Closed by https://github.com/jump-dev/MathOptInterface.jl/pull/1419

https://github.com/jump-dev/MathOptInterface.jl/blob/79c792718d091dccd0de4395a2c70bdc49b9b95f/src/Test/test_model.jl#L606-L638

**Comment by blegat** [comment]
Nice, this should catch a few bugs in solvers
